#%%
"""
test_replicate_ETAS_time.py
============================
Trains RECAST's RecurrentTPP on synthetic ETAS catalogs (generated by
generate_etas_synthetic.py) and evaluates how faithfully the neural model
replicates the TEMPORAL component of the generative process, ignoring space.

WHAT THIS TESTS:
    - Can a neural temporal point process (RecurrentTPP) recover the inter-event
      time statistics of a known parametric model (ETAS), on its own?
    - How much data does RecurrentTPP need before it matches the true ETAS
      temporal NLL on held-out sequences?  (Section 13: data quantity sweep)

TIME-ONLY DESIGN:
    RecurrentTPP is instantiated with spatial_weight=0.0 (see
    eq/models/recurrent.py), so the spatial (x, y) term never contributes to
    the training loss — only the Weibull-mixture inter-event-time distribution
    is fit. x, y are still encoded as real observed RNN inputs during training
    (they carry signal about the true process), but sampled locations are not
    fed back into the RNN during generation, since the spatial decoder is
    never trained to produce anything meaningful.

    The comparison baseline is NOT a re-fitted RECAST ETAS() model. It is the
    TRUE analytic temporal ETAS kernel evaluated directly from TRUE_PARAMS
    (the parameters etas_2 used to generate the catalogs) — no inversion
    needed. Section 9's cumulative-count forecast additionally compares
    against etas_2's own simulate_catalog_continuation() output, reading off
    only the temporal marginal (event counts) and ignoring its spatial output.

WORKFLOW:
    1. Load etas_2 synthetic catalogs from parquet + metadata JSON.
    2. Project each catalog's lat/lon events into local km coordinates and
       build RECAST Sequence objects.
    3. Split into train / val / test (60 / 20 / 20).
    4. Derive the true analytic temporal ETAS kernel from TRUE_PARAMS (no
       fitting) — gives a parametric baseline NLL to compare against.
    5. Train RecurrentTPP (spatial_weight=0.0) on the same sequences.
    6. Compare: NLL table, cumulative forecast bands, inter-event time mixture,
       conditional intensity figure.
    7. Data quantity sweep: retrain with progressively fewer sequences to find
       the crossover point where RECAST beats the true ETAS temporal NLL.

PREREQUISITE:
    Run generate_etas_synthetic.py first to create:
        case_studies/etas2_synthetic/raw_catalogs.parquet
        case_studies/etas2_synthetic/true_params.json
"""

import json
import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader

torch.set_num_threads(1)   # prevents PyTorch from spawning extra threads on CPU

import eq
from plot_helpers import plot_time_mixture

# ── Paths ───────────────────────────────────────────────────────────────────────
HOME_DIR  = "/home/a01738353/2024_NEHRP/RECAST/"
DATA_DIR  = f"{HOME_DIR}case_studies/etas2_synthetic/"
SAVE_DIR  = f"{HOME_DIR}results/replicate_ETAS_time/"
FIGS_DIR  = f"{HOME_DIR}figs/replicate_ETAS_time/"

for d in [SAVE_DIR, FIGS_DIR]:
    os.makedirs(d, exist_ok=True)


#%%
# ─── Section 1: Load metadata ──────────────────────────────────────────────────
# The JSON written by generate_etas_synthetic.py holds all constants we need:
# true ETAS parameters, polygon centroid, km/degree conversion factors, etc.
# Reading them here ensures test_replicate_ETAS.py and generate_etas_synthetic.py
# always agree on the coordinate system without any hardcoding.

with open(f"{DATA_DIR}true_params.json") as f:
    meta = json.load(f)

TRUE_PARAMS  = meta["true_params"]    # dict of raw etas_2 parameter values
LAT_CTR      = meta["lat_ctr"]        # polygon centroid latitude  [°N]
LON_CTR      = meta["lon_ctr"]        # polygon centroid longitude [°W, negative]
KM_PER_LAT   = meta["km_per_lat"]     # ≈ 111.1 km per degree latitude
KM_PER_LON   = meta["km_per_lon"]     # ≈ 91.0 km per degree longitude at 35°N
HALF_KM_LAT  = meta["half_km_lat"]    # ≈ 222 km — N/S half-extent of box
HALF_KM_LON  = meta["half_km_lon"]    # ≈ 182 km — E/W half-extent of box
BOX_AREA_KM2 = meta["box_area_km2"]   # ≈ 161 000 km²
T_DAYS       = meta["t_days"]         # catalog window length = 30 days
MC           = meta["mc"]             # magnitude of completeness = 3.6
MAG_MAX      = meta["mag_max"]        # 8.0 — upper bound for ContinuousMarks
N_CATALOGS   = meta["n_catalogs"]     # 300

# True ETAS parameters in RECAST-comparable units (pre-computed in generation script).
# We print these at the end alongside RECAST's fitted values.
TRUE_P     = meta["recast_p_true"]       # Omori p = 1 + omega
TRUE_C     = meta["recast_c_true"]       # Omori c [days]
TRUE_ALPHA = meta["recast_alpha_true"]   # = a in etas_2 = alpha in RECAST
TRUE_MU    = meta["recast_mu_rate_true"] # background rate [events/day] over the box
# Spatial parameters — read directly from the true_params dict.
TRUE_D     = 10 ** meta["true_params"]["log10_d"]  # base spatial length scale [km]
TRUE_GAMMA = meta["true_params"]["gamma"]           # magnitude scaling of cluster radius
TRUE_RHO   = meta["true_params"]["rho"]             # spatial power-law decay exponent
# Equivalent-circle radius so that π·R_bg² = box area; makes the background
# density μ/(π·R_bg²) consistent with the uniform-over-box generating process.
TRUE_R_BG  = (BOX_AREA_KM2 / math.pi) ** 0.5       # ≈ 227 km

MIN_EVENTS = 10   # drop catalogs with fewer events than this (too sparse to train on)

print(f"Loaded metadata from {DATA_DIR}true_params.json")
print(f"  True p={TRUE_P:.2f}  c={TRUE_C:.5f} d  alpha={TRUE_ALPHA:.2f}")
print(f"  True mu={TRUE_MU:.3f} events/day (over {BOX_AREA_KM2:.0f} km²)")
print(f"  True d={TRUE_D:.4f} km  gamma={TRUE_GAMMA:.2f}  rho={TRUE_RHO:.2f}  R_bg={TRUE_R_BG:.1f} km")
print(f"  T_DAYS={T_DAYS}  MC={MC}  MAG_MAX={MAG_MAX}")


#%%
# ─── Section 2: Load parquet and convert to RECAST Sequences ──────────────────
#
# etas_2 outputs a DataFrame with columns:
#     catalog_id, latitude [°N], longitude [°W], time [datetime], magnitude
#
# RECAST needs a Sequence object with:
#     inter_times  — time gaps between consecutive events [days]; shape (n+1,)
#                    inter_times[0]  = gap from window start (0.0) to first event
#                    inter_times[-1] = gap from last event to window end (T_DAYS)
#     t_start      — 0.0 (we define each window start as time zero)
#     mag          — ContinuousMarks object wrapping a (n,) float32 tensor
#     x_loc        — km east  of polygon centroid; shape (n,) float32
#     y_loc        — km north of polygon centroid; shape (n,) float32
#
# Coordinate projection:
#     x_km = (longitude − LON_CTR) × KM_PER_LON     east is positive
#     y_km = (latitude  − LAT_CTR) × KM_PER_LAT     north is positive
#
# This is the same flat-Earth (equirectangular) projection used in
# test_case_study.py:load_mainshock_sequence().  It's accurate to ~0.1% over
# the ~400 km extent of our box.

def catalog_to_sequence(df_group):
    """Convert one etas_2 catalog (a sub-DataFrame) to a RECAST Sequence.

    Args:
        df_group: DataFrame rows for a single catalog_id.
                  Expected columns: latitude, longitude, time, magnitude.

    Returns:
        eq.data.Sequence  with inter_times, mag (ContinuousMarks), x_loc, y_loc.
        None if the group has fewer than MIN_EVENTS events.
    """
    # Sort by time (etas_2 may not guarantee order when aftershock generations merge)
    df = df_group.sort_values("time").reset_index(drop=True)
    df = df[df.magnitude >= MC].reset_index(drop=True)

    if len(df) < MIN_EVENTS:
        return None

    # ── Project geographic coordinates to km offsets from the polygon centroid ─
    # "East" and "North" here match the convention in test_case_study.py so that
    # models trained on different datasets share the same spatial semantics.
    x_km = ((df.longitude.values - LON_CTR) * KM_PER_LON).astype(np.float32)
    y_km = ((df.latitude.values  - LAT_CTR) * KM_PER_LAT).astype(np.float32)

    # ── Convert datetime → fractional days since window start ─────────────────
    # Each catalog was generated over a T_DAYS-day window.  We measure time
    # from the window start (t_start = 0.0).  All etas_2 events fall strictly
    # in the open interval (0, T_DAYS), so the first and last inter-times are > 0.
    t_window_start = df["time"].iloc[0].replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    # Round window start to nearest day boundary — etas_2 guarantees events are
    # in (window_start, window_end) so the exact value doesn't affect relative times.
    arrival_days = (df["time"] - t_window_start).dt.total_seconds().values / 86400.0
    # Safety clip: keep all arrivals strictly inside (0, T_DAYS) to avoid
    # zero or negative inter-times at floating-point boundaries.
    arrival_days = np.clip(arrival_days, 1e-6, T_DAYS - 1e-6)

    # inter_times[0]   = arrival_days[0] − 0.0          (gap from window start)
    # inter_times[i]   = arrival_days[i] − arrival_days[i-1]   (event to event)
    # inter_times[-1]  = T_DAYS − arrival_days[-1]       (gap to window end)
    inter_times = np.diff(arrival_days, prepend=[0.0], append=[float(T_DAYS)])

    # ── Wrap magnitudes in ContinuousMarks ─────────────────────────────────────
    # ContinuousMarks stores: the raw magnitude values + (mc, mag_max) bounds
    # used by RecurrentTPP to compute the Gutenberg-Richter log-probability.
    # The ETAS model ignores the bounds and reads only the raw .values tensor.
    mag = eq.data.ContinuousMarks(
        df.magnitude.values.astype(np.float32),
        bounds     = [MC, MAG_MAX],
        nll_bounds = [MC, MAG_MAX],
    )

    return eq.data.Sequence(
        inter_times,
        t_start = 0.0,     # all sequences start at t=0 (window start)
        mag     = mag,
        x_loc   = torch.tensor(x_km),
        y_loc   = torch.tensor(y_km),
    )


raw_df = pd.read_parquet(f"{DATA_DIR}raw_catalogs.parquet")
print(f"Loaded {len(raw_df):,} events from {raw_df.catalog_id.nunique()} catalogs")

# Convert every catalog group to a Sequence (or None if too sparse)
sequences = []
for cat_id, group in raw_df.groupby("catalog_id"):
    seq = catalog_to_sequence(group)
    if seq is not None:
        sequences.append(seq)

print(f"Sequences after ≥{MIN_EVENTS}-event filter: {len(sequences)} / {N_CATALOGS}")

# ── Train / val / test split (60 / 20 / 20) ────────────────────────────────────
# We split by index (not by time) because each catalog is an independent
# realisation — there is no temporal ordering between catalogs to preserve.
n_total = len(sequences)
n_train = int(0.60 * n_total)
n_val   = int(0.20 * n_total)

train_seqs = sequences[:n_train]
val_seqs   = sequences[n_train : n_train + n_val]
test_seqs  = sequences[n_train + n_val :]

train_ds = eq.data.InMemoryDataset(train_seqs)
val_ds   = eq.data.InMemoryDataset(val_seqs)
test_ds  = eq.data.InMemoryDataset(test_seqs)

print(f"Split: {len(train_ds)} train / {len(val_ds)} val / {len(test_ds)} test")

# Quick sanity check on the first training sequence
s0 = train_ds[0]
print(f"\nFirst training sequence:")
print(f"  Events   : {s0.num_events}")
print(f"  Duration : {s0.t_end:.2f} days (should be ≈{T_DAYS})")
print(f"  x range  : [{s0.x_loc.min():.1f}, {s0.x_loc.max():.1f}] km")
print(f"  y range  : [{s0.y_loc.min():.1f}, {s0.y_loc.max():.1f}] km")
print(f"  mag range: [{s0.mag.numpy().min():.1f}, {s0.mag.numpy().max():.1f}]")

#%%
# ── Verify: inspect one loaded sequence — stem plot + spatial scatter ───────────
# Change VERIFY_SEQ_IDX to view a different sequence (0 to len(sequences)-1).

VERIFY_SEQ_IDX = 11

_seq = sequences[VERIFY_SEQ_IDX]
_t   = _seq.arrival_times.numpy()
_m   = _seq.mag.numpy()
_x   = _seq.x_loc.numpy()
_y   = _seq.y_loc.numpy()

fig, (ax_t, ax_s) = plt.subplots(1, 2, figsize=(10, 5))
fig.suptitle(
    f"Loaded Sequence {VERIFY_SEQ_IDX}  ({_seq.num_events} events)",
    fontsize=12,
)

# Top: time-magnitude stem plot
markerline, stemlines, baseline = ax_t.stem(
    _t, _m, markerfmt="C0o", linefmt="C0-", basefmt="k-",
)
markerline.set_visible(False)   # stem markers can't vary in size; use scatter instead
plt.setp(stemlines, linewidth=0.7, alpha=0.6)
ax_t.scatter(_t, _m, s=20 + 15 * (_m - MC)**2, color="C0", zorder=3)
ax_t.axhline(MC, color="gray", linestyle="--", linewidth=0.8, label=f"Mc = {MC}")
ax_t.set_xlim(-1, T_DAYS)
ax_t.set_ylim(1,7)
ax_t.set_xlabel("Time [days since window start]")
ax_t.set_ylabel("Magnitude")
ax_t.legend(fontsize=9)

# Bottom: spatial distribution coloured by magnitude
sc = ax_s.scatter(
    _x, _y,
    c=_m, cmap="hot_r",
    s=20 + 15 * (_m - MC)**2,
    vmin=MC, vmax=max(_m.max(), MC + 1),
    alpha=0.8, edgecolors="k", linewidths=0.3,
)
plt.colorbar(sc, ax=ax_s, label="Magnitude")
ax_s.scatter(_x[0], _y[0], marker="*", s=150, color="red", zorder=5, label="First event")
ax_s.axhline(0, color="k", lw=0.5, ls="--")
ax_s.axvline(0, color="k", lw=0.5, ls="--")
ax_s.set_xlim(-HALF_KM_LON, HALF_KM_LON)
ax_s.set_ylim(-HALF_KM_LAT, HALF_KM_LAT)
ax_s.set_xlabel("East of box center [km]")
ax_s.set_ylabel("North of box center [km]")
ax_s.set_aspect("equal", adjustable="box")
ax_s.legend(fontsize=9)

plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/verify_sequence_{VERIFY_SEQ_IDX:03d}.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 3: Normalization statistics ───────────────────────────────────────
# RecurrentTPP encodes events as:
#   time  → log(τ) − log(τ_mean)          (log inter-time, zero-centred)
#   space → (x − x_mean) / x_std,  same for y
#   mag   → (m − Mc)                       (no normalisation needed; already ≥ 0)
#
# We compute τ_mean, x_mean, x_std, y_mean, y_std from the TRAINING set only
# and register them as fixed buffers in the model.  Applying them to val/test
# sequences is valid because ETAS is stationary: the population statistics are
# the same everywhere in the box and across all time windows.

all_x   = np.concatenate([s.x_loc.numpy() for s in train_ds])
all_y   = np.concatenate([s.y_loc.numpy() for s in train_ds])
all_tau = np.concatenate([s.inter_times[:-1].numpy() for s in train_ds])

# x_mean ≈ 0, y_mean ≈ 0 because etas_2 uses a uniform background and the
# box is centred on (LAT_CTR, LON_CTR).  We set them explicitly to 0 rather
# than estimating them to avoid fitting noise.
x_mean, y_mean = 0.0, 0.0
x_std    = float(all_x.std())
y_std    = float(all_y.std())
tau_mean = float(all_tau.mean())

print(f"Normalization (from {len(train_ds)} training sequences):")
print(f"  tau_mean = {tau_mean:.4f} days")
print(f"  x_std    = {x_std:.1f} km")
print(f"  y_std    = {y_std:.1f} km")


#%%
# ─── Section 5: True temporal ETAS — analytic baseline (no fitting) ───────────
#
# We compare RECAST directly against etas_2's TRUE generating temporal kernel
# (TRUE_PARAMS), not a re-fitted approximation via RECAST's own ETAS() class.
# Since these parameters generated the data, no inversion is needed.
#
# TWO UNIT PITFALLS THAT MUST MATCH etas_2's OWN CONVENTION EXACTLY
# (etas_2/etas/inversion.py:expected_aftershocks / triggering_kernel):
#
#   1. Productivity uses a NATURAL exponential, not base 10:
#          number_factor(m) = k0 · exp(a·(m − Mc))
#      RECAST's own classical ETAS() class instead uses 10**(alpha·Δm). An
#      earlier version of this script mistakenly plugged etas_2's `a` into
#      that base-10 formula, which inflates productivity by orders of
#      magnitude for any event above Mc (e.g. Δm=2.5: exp(1.69·2.5)≈72 vs.
#      10**(1.69·2.5)≈16,700) and produced a nonsensical mean NLL (~50+,
#      dominated by a few catastrophic outlier sequences with larger
#      mainshocks).
#
#   2. etas_2's spatial kernel is NOT normalized to integrate to 1 over the
#      plane. Marginalizing it out over all space contributes its own
#      magnitude-dependent factor:
#          area_factor(m) = (π / ρ) · (d · exp(γ·(m − Mc)))^(−ρ)
#      (same factor `expected_aftershocks()` uses). Dropping this factor
#      (as an earlier version did) silently changes the effective
#      productivity scale.
#
# The compensator below calls etas_2's own expected_aftershocks() directly
# (rather than re-deriving the incomplete-gamma taper integral by hand), so
# its normalization is guaranteed to match the generative model exactly. The
# instantaneous intensity uses the same number_factor/area_factor building
# blocks, just with the un-integrated kernel exp(−Δt/τ)·(Δt+c)^−(1+ω).

from etas.inversion import expected_aftershocks

TRUE_K0  = 10 ** TRUE_PARAMS["log10_k0"]    # base productivity [etas_2 units]
TRUE_TAU = 10 ** TRUE_PARAMS["log10_tau"]   # exponential taper scale [days]
TRUE_OMEGA = TRUE_PARAMS["omega"]           # Omori shape; p = 1 + omega

# theta order matches etas_2's own convention (etas/inversion.py:parameter_dict2array)
_THETA = (
    TRUE_PARAMS["log10_k0"], TRUE_ALPHA, TRUE_PARAMS["log10_c"], TRUE_OMEGA,
    TRUE_PARAMS["log10_tau"], TRUE_PARAMS["log10_d"], TRUE_GAMMA, TRUE_RHO,
)

print(f"\nTrue temporal ETAS parameters (etas_2 generating values, no fitting):")
print(f"  p={TRUE_P:.3f}  c={TRUE_C:.5f} d  k0={TRUE_K0:.5f}  a={TRUE_ALPHA:.3f}  "
      f"mu={TRUE_MU:.4f} events/day")


def _parent_coefficient(m):
    """number_factor(m) · area_factor(m): the combined magnitude-dependent
    coefficient in front of the (un-integrated) temporal kernel, after
    marginalizing etas_2's spatial kernel out over all space."""
    number_factor = TRUE_K0 * np.exp(TRUE_ALPHA * (m - MC))
    area_factor = np.pi / TRUE_RHO * (TRUE_D * np.exp(TRUE_GAMMA * (m - MC))) ** (-TRUE_RHO)
    return number_factor * area_factor


def etas_temporal_intensity(seq, mu, t_grid):
    """Temporal-marginal intensity: λ(t) = μ + Σ_{j<t} coef(m_j)·exp(−Δt/τ)·(Δt+c)^−(1+ω)"""
    times = seq.arrival_times.numpy()
    mags  = seq.mag.numpy()
    coef  = _parent_coefficient(mags)
    dt     = t_grid[:, None] - times[None, :]        # (T, n)
    causal = dt > 0
    dt_pos = np.maximum(dt, 0)
    kernel = np.exp(-dt_pos / TRUE_TAU) * (dt_pos + TRUE_C) ** -(1 + TRUE_OMEGA)
    return mu + (coef * kernel * causal).sum(axis=1)


def etas_temporal_compensator(seq, mu, t_grid):
    """Compensator: Λ(t) = μ·t + Σ_{j<t} expected_aftershocks(m_j; 0 → t−t_j).
    Delegates to etas_2's own expected_aftershocks() so the taper /
    incomplete-gamma normalization exactly matches the generative model."""
    times = seq.arrival_times.numpy()
    mags  = seq.mag.numpy()
    if len(times) == 0:
        return mu * t_grid
    dt = np.clip(t_grid[:, None] - times[None, :], 0.0, None)   # (T, n), non-causal → 0
    mags_b = np.broadcast_to(mags[None, :], dt.shape)
    contrib = expected_aftershocks([mags_b, np.zeros_like(dt), dt], [_THETA, MC])
    return mu * t_grid + contrib.sum(axis=1)


def true_etas_temporal_nll(seqs, mu=TRUE_MU):
    """Per-sequence temporal NLL per day, matching RecurrentTPP.nll_loss's definition:
        −[Σ log λ(t_i) − (Λ(t_end) − Λ(t_start))] / (t_end − t_start)
    Assumes t_start = 0 for every sequence (true for all catalogs built in Section 2).
    """
    nlls = []
    for seq in seqs:
        times = seq.arrival_times.numpy()
        log_lik = np.log(etas_temporal_intensity(seq, mu, times)).sum() \
            if len(times) > 0 else 0.0
        comp_end = etas_temporal_compensator(seq, mu, np.array([float(seq.t_end)]))[0]
        nlls.append(-(log_lik - comp_end) / (float(seq.t_end) - float(seq.t_start)))
    return np.array(nlls)


# ── True-ETAS test NLL (the baseline to beat) ──────────────────────────────────
test_batch = eq.data.Batch.from_list(test_seqs)
etas_test_nll = true_etas_temporal_nll(test_seqs).mean()
print(f"\nTrue ETAS temporal NLL on test set: {etas_test_nll:.4f} per day")


#%%
# ─── Section 6: Define and train RecurrentTPP ─────────────────────────────────
#
# Architecture (from eq/models/recurrent.py):
#   Encoder: each event → [log(τ) − log(τ_mean), (x−x_mean)/x_std,
#                           (y−y_mean)/y_std, (m−Mc)]  — a 4-dimensional vector
#   RNN (GRU): encodes event history → context vector of size context_size
#   Decoders (hypernets):
#     hypernet_time → Weibull mixture parameters (num_components_time components)
#     hypernet_xy   → 2D Gaussian mixture parameters with Cholesky covariance
#     hypernet_mag  → Gutenberg-Richter parameters (effectively learns b-value)
#
# NLL loss returned per sequence per day:
#   − [time_weight × log p(inter_times) + spatial_weight × log p(x_loc, y_loc)
#      + log S(t_last) − log S(t_first)]  /  (t_end − t_nll_start)
#
# TIME-ONLY FOCUS: spatial_weight=0.0 means the spatial term never contributes
# to the loss, so hypernet_xy stays untrained/unused — the model is trained
# purely on the temporal (Weibull mixture) marginal. x, y are still fed into
# the RNN as encoder inputs from the real observed sequence (they carry signal
# useful for predicting future times), but sampled locations are not fed back
# during generation (see RecurrentTPP.sample()) since the spatial decoder was
# never trained to produce anything meaningful.
#
# MODEL SIZE: We use a smaller model than test_case_study.py (context_size=64
# vs 256) because the synthetic sequences are shorter (30 vs 365 days) and
# the ETAS dynamics are simpler than real multi-sequence global seismicity.

model = eq.models.RecurrentTPP(
    context_size         = 64,    # RNN hidden-state dimension
    num_components_time  = 8,     # Weibull mixture components for time
    num_components_space = 16,    # Gaussian mixture components for space
    tau_mean             = tau_mean,
    x_mean               = x_mean,
    y_mean               = y_mean,
    x_std                = x_std,
    y_std                = y_std,
    spatial_dist         = 'gaussian', # 'student_t'
    spatial_weight        = 0.0,   # time-only: spatial term excluded from the loss
)
print(f"RecurrentTPP parameters: {sum(p.numel() for p in model.parameters()):,}")
#%%
# ── Training configuration ──────────────────────────────────────────────────────
_RETRAIN_   = True   # set False to skip training and just load the saved checkpoint
EPOCHS      = 900
BATCH_SIZE  = 32


if _RETRAIN_:
    device    = 'cuda' if torch.cuda.is_available() else 'cpu'
    model     = model.to(device)
    print(f"Training RecurrentTPP on: {device}")

    optimizer    = torch.optim.Adam(model.parameters(), lr=5e-4)
    scheduler    = CosineAnnealingLR(optimizer, T_max=EPOCHS)
    train_loader = DataLoader(
        train_ds,
        batch_size  = BATCH_SIZE,
        shuffle     = True,
        collate_fn  = eq.data.Batch.from_list,   # no jitter (see note above)
    )
    val_batch = eq.data.Batch.from_list(val_seqs).to(device)

    train_losses, val_losses = [], []
    model.train()
    for epoch in range(EPOCHS):
        epoch_losses = []
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            nll = model.nll_loss(batch).mean()
            nll.backward()
            # Clip gradients to prevent parameter explosions (especially early on
            # when the context vectors are near-random and spatial NLL can spike).
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_losses.append(nll.item())

        # Validation NLL — computed without gradients on the full validation set.
        with torch.no_grad():
            v_nll = model.nll_loss(val_batch).mean().item()

        epoch_mean = float(np.mean(epoch_losses))
        train_losses.append(epoch_mean)
        val_losses.append(v_nll)
        scheduler.step()

        if (epoch + 1) % 25 == 0:
            print(f"Epoch {epoch+1:3d}  train={epoch_mean:.4f}  val={v_nll:.4f}")

    torch.save(model.state_dict(), f"{SAVE_DIR}/recast_etas2.pt")

    fig, ax = plt.subplots(figsize=(9, 3))
    ax.plot(train_losses, label='train', color='steelblue', lw=0.9)
    ax.plot(val_losses,   label='val',   color='orange',    lw=0.9)
    ax.axhline(etas_test_nll, ls='--', color='red', lw=1.2, label='ETAS temporal NLL')
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Mean NLL / day")
    ax.set_title("RecurrentTPP training loss  (dashed = ETAS temporal baseline)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/recast_training_loss.png", dpi=150, bbox_inches='tight')
    plt.show()


#%%
# ─── Section 7: Load trained model ────────────────────────────────────────────
map_location = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.cpu()
model.load_state_dict(torch.load(f"{SAVE_DIR}/recast_etas2.pt",
                                  map_location='cpu'))
model.eval()
print(f"Loaded checkpoint from {SAVE_DIR}/recast_etas2.pt")


#%%
# ─── Section 8: NLL comparison table ──────────────────────────────────────────
# Evaluate both models on the held-out test set and print a comparison.
# Both NLLs are now purely temporal (spatial_weight=0.0 on RECAST, analytic
# true-ETAS temporal marginal on the other side), so they're directly
# comparable — no unit/weighting caveat needed.

with torch.no_grad():
    model = model.cpu()
    test_batch = test_batch.to('cpu')
    recast_test_nll = model.nll_loss(test_batch).mean().item()

print("\n" + "="*55)
print(f"  {'Model':30s}  {'NLL / day':>10s}")
print(f"  {'-'*30}  {'-'*10}")
print(f"  {'True ETAS (temporal)':30s}  {etas_test_nll:>10.4f}")
print(f"  {'RecurrentTPP (temporal only)':30s}  {recast_test_nll:>10.4f}")
print("="*55)
print("  Lower = better at predicting held-out inter-event times.")


#%%
# ─── Section 9: Cumulative count forecast — etas_2 (true model) vs. RECAST ───
# Both forecasts are conditioned on the SAME first `condition_days` of seq_ref.
#
# Left panel:  etas_2's simulate_catalog_continuation() using TRUE_PARAMS —
#              the actual generative model, not a re-fit approximation.
# Right panel: RECAST RecurrentTPP sampled forward from the same history.
#
# Conversion: cond_seq (km offsets, fractional days) → lat/lon DataFrame for
# etas_2 → simulated events → fractional days for the count grid.

import datetime as dt
import logging
from shapely.geometry import Polygon as ShapelyPolygon
from etas.simulation import simulate_catalog_continuation

logging.getLogger("etas").setLevel(logging.WARNING)  # suppress etas_2 verbosity

condition_days = 5
FORECAST_BATCH = 200

# ── Reconstruct the study-area polygon from metadata ─────────────────────────
# etas_2 uses (lat, lon) as (x, y) internally (consistent with its gpd calls).
LAT_MIN = LAT_CTR - HALF_KM_LAT / KM_PER_LAT
LAT_MAX = LAT_CTR + HALF_KM_LAT / KM_PER_LAT
LON_MIN = LON_CTR - HALF_KM_LON / KM_PER_LON
LON_MAX = LON_CTR + HALF_KM_LON / KM_PER_LON
polygon = ShapelyPolygon([
    [LAT_MIN, LON_MIN], [LAT_MAX, LON_MIN],
    [LAT_MAX, LON_MAX], [LAT_MIN, LON_MAX],
])
beta_main = np.log(10) * meta["richter_b"]

# Arbitrary epoch — only relative times matter for the simulation.
T_REF = dt.datetime(2020, 1, 1, 0, 0, 0)

# ── Reference sequence and split ──────────────────────────────────────────────
seq_ref       = test_ds[1]
forecast_days = float(seq_ref.t_end) - condition_days
cond_seq      = seq_ref.get_subsequence(seq_ref.t_start, condition_days)
print(f"Reference sequence: {seq_ref.num_events} total events")
print(f"  Conditioning on  t ∈ [0, {condition_days:.0f}) days ({cond_seq.num_events} events)")
print(f"  Forecasting      t ∈ [{condition_days:.0f}, {seq_ref.t_end:.0f}] days")

T_SHOW = float(forecast_days)
N_GRID = 300
t_grid = np.linspace(0, T_SHOW, N_GRID)


def cond_seq_to_df(seq):
    """Convert a RECAST Sequence to an etas_2 auxiliary_catalog DataFrame.

    Converts fractional-day arrival times to datetimes relative to T_REF, and
    km offsets back to lat/lon using the box centroid and scale factors.
    """
    times = seq.arrival_times.numpy()
    lats  = seq.y_loc.numpy() / KM_PER_LAT + LAT_CTR
    lons  = seq.x_loc.numpy() / KM_PER_LON + LON_CTR
    mags  = seq.mag.numpy()
    return pd.DataFrame({
        'latitude':  lats,
        'longitude': lons,
        'time':      [T_REF + dt.timedelta(days=float(t)) for t in times],
        'magnitude': mags,
        'xi_plus_1': 1.0,
    })


def forecast_cumulative(batch, t_cut, t_grid):
    """Cumulative event count relative to t_cut for each sampled RECAST trajectory.

    Args:
        batch  : Batch returned by model.sample().
        t_cut  : Conditioning cutoff time (fractional days).
        t_grid : 1-D array of relative times at which to evaluate the count.

    Returns:
        cum: int array of shape (batch_size, len(t_grid)).
    """
    cum = np.zeros((batch.batch_size, len(t_grid)), dtype=int)
    for i in range(batch.batch_size):
        n        = int(batch.end_idx[i])
        times    = batch.arrival_times[i, :n].numpy()
        fore_rel = np.sort(times[times > t_cut] - t_cut)
        cum[i]   = np.searchsorted(fore_rel, t_grid, side='right')
    return cum


# Observed step function for the reference sequence
obs_times_rel = seq_ref.arrival_times.numpy() - condition_days
obs_fore      = np.sort(obs_times_rel[obs_times_rel > 0])
obs_cum       = np.searchsorted(obs_fore, t_grid, side='right')

# ── etas_2 conditional forecast (true generative model, TRUE_PARAMS) ──────────
print(f"Sampling {FORECAST_BATCH} etas_2 trajectories (true generative model)...")
cond_df  = cond_seq_to_df(cond_seq)
aux_end  = T_REF + dt.timedelta(days=condition_days)
sim_end  = T_REF + dt.timedelta(days=float(seq_ref.t_end))

etas2_cum = np.zeros((FORECAST_BATCH, len(t_grid)), dtype=int)
for sim_id in range(FORECAST_BATCH):
    sim = simulate_catalog_continuation(
        auxiliary_catalog = cond_df,
        auxiliary_start   = T_REF,
        auxiliary_end     = aux_end,
        polygon           = polygon,
        simulation_end    = sim_end,
        parameters        = TRUE_PARAMS,
        mc                = MC,
        beta_main         = beta_main,
        m_max             = MAG_MAX,
        filter_polygon    = False,   # skip geopandas filtering — saves ~30 % time
        approx_times      = True,    # faster Omori inversion approximation
    )
    sim_fore   = sim[sim['time'] > aux_end]
    times_days = np.array(
        [(t - T_REF).total_seconds() / 86400.0 for t in sim_fore['time']]
    )
    fore_rel = np.sort(times_days - condition_days)
    fore_rel = fore_rel[fore_rel > 0]
    etas2_cum[sim_id] = np.searchsorted(fore_rel, t_grid, side='right')
    if (sim_id + 1) % 50 == 0:
        print(f"  {sim_id + 1}/{FORECAST_BATCH}")

e_q10, e_q25, e_q75, e_q90 = np.percentile(etas2_cum, [10, 25, 75, 90], axis=0)

# ── RECAST conditional forecast ───────────────────────────────────────────────
print(f"Sampling {FORECAST_BATCH} RECAST trajectories...")
model.eval()
with torch.no_grad():
    recast_pred = model.sample(
        batch_size       = FORECAST_BATCH,
        duration         = forecast_days,
        t_start          = condition_days,
        past_seq         = cond_seq,
        mag_completeness = MC,
    )
recast_cum = forecast_cumulative(recast_pred, condition_days, t_grid)
r_q10, r_q25, r_q75, r_q90 = np.percentile(recast_cum, [10, 25, 75, 90], axis=0)

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4), sharey=True)
fig.suptitle(
    f"Cumulative Count Forecast — {condition_days} Days of Conditioning",
    fontsize=11,
)

for ax, cum_q10, cum_q25, cum_q75, cum_q90, color, label in [
    (axes[0], e_q10, e_q25, e_q75, e_q90, 'darkorange',
     f'etas_2 (true model, {FORECAST_BATCH} samples)'),
    (axes[1], r_q10, r_q25, r_q75, r_q90, 'steelblue',
     f'RECAST RecurrentTPP ({FORECAST_BATCH} samples)'),
]:
    ax.fill_between(t_grid, cum_q10, cum_q90, alpha=0.20, color=color, label='q10–q90')
    ax.fill_between(t_grid, cum_q25, cum_q75, alpha=0.45, color=color, label='q25–q75')
    ax.step(np.concatenate([[0], t_grid]),
            np.concatenate([[0], obs_cum]),
            where='post', color='k', linewidth=1.8, label='Ref seq (observed)', zorder=5)
    ax.set_xlabel("Days after conditioning cutoff")
    ax.set_ylabel("Cumulative events")
    ax.set_title(label, fontsize=9)
    ax.legend(fontsize=8)
    ax.set_xlim(0, T_SHOW)
    ax.set_ylim(bottom=0)

plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/forecast_cumulative.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 10: Inter-event time distributions ───────────────────────────────
# Compare the inter-event time density learned by RECAST against the empirical
# histogram from all training sequences.
#
# RECAST's time decoder is a Weibull mixture (plot_time_mixture from
# plot_helpers.py).  We show two contexts:
#   Left:  zero context — the model's "prior" before seeing any events.
#          Should match the average inter-event distribution from training.
#   Right: context after conditioning on the reference sequence (first half).
#          Should show shorter inter-times if a burst just occurred (Omori effect).

# Aggregate inter-event times from 50 training sequences for the histogram
training_inter = np.concatenate([
    train_ds[i].inter_times[:-1].numpy()
    for i in range(min(50, len(train_ds)))
])

# Inter-event times after the conditioning cutoff from the reference sequence
post_cond_inter = cond_seq.inter_times[:-1].numpy()
# Also grab post-condition events from seq_ref for a richer histogram
post_ref = seq_ref.get_subsequence(condition_days, seq_ref.t_end)
post_ref_inter = post_ref.inter_times[:-1].numpy() if post_ref.num_events > 0 else np.array([])

# Context vectors
context_zero = torch.zeros(1, 1, model.context_size)
cond_batch   = eq.data.Batch.from_list([cond_seq])
with torch.no_grad():
    context_cond = model.get_context(cond_batch)[:, [-1], :]   # last context vector

T_MAX = 5.0   # x-axis limit for the density plot [days]
Y_MAX = 40    # y-axis limit for density

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

for ax, ctx, title, obs_inter, obs_label in [
    (axes[0], context_zero, 'Prior (zero context)',
     training_inter, f"Training sequences (50 of {len(train_ds)})"),
    (axes[1], context_cond,
     f'After conditioning ({cond_seq.num_events} events, t=0–{condition_days:.0f} d)',
     post_ref_inter, "Reference seq (post-condition)"),
]:
    plot_time_mixture(model, ctx, ax, t_max=T_MAX)
    if len(obs_inter) > 0:
        # Log-spaced bins to show the long tail
        bins = np.logspace(-3, np.log10(T_MAX * 3), 60)
        ax.hist(obs_inter, bins=bins, density=True,
                alpha=0.35, color='red', rwidth=0.9, label=obs_label)
    ax.set_xlabel("Inter-event time (days)")
    ax.set_ylabel("Density")
    ax.set_xlim([0, T_MAX * 0.2])
    ax.set_ylim([0, Y_MAX*0.2])
    ax.set_title(title)
    ax.legend(fontsize=8)

plt.suptitle("Weibull inter-event time mixture — RECAST", fontsize=12)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/time_mixture.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 14: Conditional intensity figure (paper Fig. 2 equivalent) ───────
# Three-panel figure matching Dascher-Cousineau et al. (2023) Figure 2:
#
#   A (top-left):    Magnitude scatter plot; right axis shows N(t) (observed
#                    cumulative count) alongside the ETAS and RECAST compensators
#                    Λ(t) = ∫₀ᵗ λ(s) ds.  A good model has Λ(t) ≈ N(t).
#
#   B (bottom-left): ETAS and RECAST conditional intensity λ(t) on a log scale.
#                    Panels A and B share the time axis.
#
#   C (right):       Histogram of per-catalog NLL differences
#                    log L̃_RECAST − log L̃_ETAS for every train and test sequence.
#                    Values > 0 mean ETAS preferred; < 0 mean RECAST preferred.
#
# ETAS intensity / compensator here are the analytic true-parameter functions
# defined in Section 5 (etas_temporal_intensity / etas_temporal_compensator),
# evaluated at the true generating TRUE_PARAMS — no fitting involved.
# RECAST uses model.evaluate_intensity() and model.evaluate_compensator().

import matplotlib.gridspec as gridspec


# ── Use the same reference sequence as Section 9 ─────────────────────────────
_seq  = seq_ref
_arr  = _seq.arrival_times.numpy()
_mags = _seq.mag.numpy()

# Dense time grid for ETAS (uniform); RECAST uses its own internal grid
_t_fine = np.linspace(float(_seq.t_start) + 1e-4, float(_seq.t_end) - 1e-4, 3000)

etas_int_vals  = etas_temporal_intensity(_seq, TRUE_MU, _t_fine)
etas_comp_vals = etas_temporal_compensator(_seq, TRUE_MU, _t_fine)

model.eval()
with torch.no_grad():
    _rt_int,  _ri_vals  = model.evaluate_intensity(_seq)
    _rt_comp, _rc_vals  = model.evaluate_compensator(_seq)

_rt_int   = _rt_int.numpy();   _ri_vals  = _ri_vals.numpy()
_rt_comp  = _rt_comp.numpy();  _rc_vals  = _rc_vals.numpy()

# N(t): step function starting at 0, incrementing at each arrival
_t_Nt = np.concatenate([[0.0], _arr])
_n_Nt = np.arange(len(_t_Nt))   # 0, 1, 2, …, n_events

# ── Per-sequence NLL for Panel C ─────────────────────────────────────────────
_train_batch_c = eq.data.Batch.from_list(train_seqs)
# test_batch is already in scope from Section 5

_etas_nll_tr = true_etas_temporal_nll(train_seqs)
_etas_nll_te = true_etas_temporal_nll(test_seqs)
with torch.no_grad():
    _recast_nll_tr = model.nll_loss(_train_batch_c).numpy()
    _recast_nll_te = model.nll_loss(test_batch).numpy()

diff_train = _recast_nll_tr - _etas_nll_tr
diff_test  = _recast_nll_te - _etas_nll_te

# ── Figure ────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(14, 6))
gs  = gridspec.GridSpec(2, 2, width_ratios=[2.2, 1], hspace=0.05, wspace=0.38)
ax_A = fig.add_subplot(gs[0, 0])
ax_B = fig.add_subplot(gs[1, 0], sharex=ax_A)
ax_C = fig.add_subplot(gs[:, 1])

# ── A: magnitude scatter (left axis) + N(t) / Λ(t) (right axis) ──────────────
ax_A.scatter(_arr, _mags, s=(_mags - MC + 0.5) ** 2 * 12,
             c='gray', alpha=0.55, zorder=2)
ax_A.set_ylabel("Magnitude")
ax_A.set_ylim(MC - 0.3, _mags.max() + 0.7)
plt.setp(ax_A.get_xticklabels(), visible=False)
ax_A.text(0.01, 0.97, 'A', transform=ax_A.transAxes,
          fontsize=12, fontweight='bold', va='top')

ax_A2 = ax_A.twinx()
ax_A2.step(_t_Nt, _n_Nt, where='post', color='gray',  lw=1.4, label='N(t)',   zorder=3)
ax_A2.plot(_t_fine,  etas_comp_vals, color='red',   lw=1.2, label='ETAS',   zorder=4)
ax_A2.plot(_rt_comp, _rc_vals,       color='black', lw=1.2, label='RECAST', zorder=4)
ax_A2.set_ylabel("Cumulative count / Λ(t)")
ax_A2.legend(fontsize=8, loc='upper left')

# ── B: conditional intensity λ(t) ─────────────────────────────────────────────
ax_B.plot(_t_fine, etas_int_vals, color='red',   lw=0.9, label='ETAS')
ax_B.plot(_rt_int, _ri_vals,      color='black', lw=0.9, label='RECAST')
ax_B.set_yscale('log')
ax_B.set_xlabel("Time (days)")
ax_B.set_ylabel("Intensity (events/day)")
ax_B.set_xlim(float(_seq.t_start), float(_seq.t_end))
ax_B.legend(fontsize=8)
ax_B.text(0.01, 0.97, 'B', transform=ax_B.transAxes,
          fontsize=12, fontweight='bold', va='top')

# ── C: per-catalog NLL difference histogram ────────────────────────────────────
_all_diffs = np.concatenate([diff_train, diff_test])
bins = np.linspace(_all_diffs.min(), _all_diffs.max(), 35)
ax_C.hist(diff_train, bins=bins, color='lightcoral', alpha=0.75, label=f'Train (n={len(diff_train)})')
ax_C.hist(diff_test,  bins=bins, color='gray',       alpha=0.75, label=f'Test  (n={len(diff_test)})')
ax_C.axvline(0, color='crimson', ls='--', lw=1.5)
ax_C.set_xlabel(
    r'$\log\tilde{\mathcal{L}}_\mathrm{RECAST} - \log\tilde{\mathcal{L}}_\mathrm{ETAS}$'
)
ax_C.set_ylabel("Number of sequences")
ax_C.legend(fontsize=8)
# Annotation matching the paper's "Preferred model" label
_xlim = ax_C.get_xlim()
_ymid = ax_C.get_ylim()[1] * 0.92
ax_C.annotate('', xy=(_xlim[0] + 0.02 * (_xlim[1]-_xlim[0]), _ymid),
              xytext=(0, _ymid),
              arrowprops=dict(arrowstyle='->', color='gray', lw=1.2))
ax_C.annotate('', xy=(_xlim[1] - 0.02 * (_xlim[1]-_xlim[0]), _ymid),
              xytext=(0, _ymid),
              arrowprops=dict(arrowstyle='->', color='gray', lw=1.2))
ax_C.text(0, _ymid, ' ETAS : RECAST ', ha='center', va='center',
          fontsize=7.5, color='gray',
          bbox=dict(fc='white', ec='none', pad=1))
ax_C.text(0.01, 0.97, 'C', transform=ax_C.transAxes,
          fontsize=12, fontweight='bold', va='top')

fig.suptitle(
    "RECAST temporal performance vs. true generating ETAS (time-only comparison)",
    fontsize=10,
)
plt.savefig(f"{FIGS_DIR}/conditional_intensity.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"\nPanel C summary:")
print(f"  Train: mean diff = {diff_train.mean():.4f}  "
      f"(+ve = ETAS preferred, −ve = RECAST preferred)")
print(f"  Test:  mean diff = {diff_test.mean():.4f}")


# %%
