#%%
"""
test_replicate_ETAS.py
======================
Trains RECAST's RecurrentTPP on synthetic ETAS catalogs (generated by
generate_etas_synthetic.py) and evaluates how faithfully the neural model
replicates the generative process.

WHAT THIS TESTS:
    - Can a neural temporal point process (RecurrentTPP) recover the statistics
      of a known parametric model (ETAS)?
    - How much data does RecurrentTPP need before it matches ETAS's NLL on
      held-out sequences?  (Section 9: data quantity sweep)

WORKFLOW:
    1. Load etas_2 synthetic catalogs from parquet + metadata JSON.
    2. Project each catalog's lat/lon events into local km coordinates and
       build RECAST Sequence objects.
    3. Split into train / val / test (60 / 20 / 20).
    4. Fit RECAST's built-in ETAS model to training sequences — gives a
       parametric baseline NLL and a parameter recovery check.
    5. Train RecurrentTPP on the same sequences.
    6. Compare: NLL table, cumulative forecast bands, inter-event time mixture,
       spatial intensity map.
    7. Data quantity sweep: retrain with progressively fewer sequences to find
       the crossover point where RECAST beats ETAS.

PREREQUISITE:
    Run generate_etas_synthetic.py first to create:
        case_studies/etas2_synthetic/raw_catalogs.parquet
        case_studies/etas2_synthetic/true_params.json
"""

import json
import os

import matplotlib.colors
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader

torch.set_num_threads(1)   # prevents PyTorch from spawning extra threads on CPU

import eq
from eq.models.etas import ETAS
from plot_helpers import plot_time_mixture, plot_xy_mixture

# ── Paths ───────────────────────────────────────────────────────────────────────
HOME_DIR  = "/home/a01738353/2024_NEHRP/RECAST/"
DATA_DIR  = f"{HOME_DIR}case_studies/etas2_synthetic/"
SAVE_DIR  = f"{HOME_DIR}results/replicate_ETAS/"
FIGS_DIR  = f"{HOME_DIR}figs/replicate_ETAS/"

for d in [SAVE_DIR, FIGS_DIR]:
    os.makedirs(d, exist_ok=True)


#%%
# ─── Section 1: Load metadata ──────────────────────────────────────────────────
# The JSON written by generate_etas_synthetic.py holds all constants we need:
# true ETAS parameters, polygon centroid, km/degree conversion factors, etc.
# Reading them here ensures test_replicate_ETAS.py and generate_etas_synthetic.py
# always agree on the coordinate system without any hardcoding.

with open(f"{DATA_DIR}true_params.json") as f:
    meta = json.load(f)

TRUE_PARAMS  = meta["true_params"]    # dict of raw etas_2 parameter values
LAT_CTR      = meta["lat_ctr"]        # polygon centroid latitude  [°N]
LON_CTR      = meta["lon_ctr"]        # polygon centroid longitude [°W, negative]
KM_PER_LAT   = meta["km_per_lat"]     # ≈ 111.1 km per degree latitude
KM_PER_LON   = meta["km_per_lon"]     # ≈ 91.0 km per degree longitude at 35°N
HALF_KM_LAT  = meta["half_km_lat"]    # ≈ 222 km — N/S half-extent of box
HALF_KM_LON  = meta["half_km_lon"]    # ≈ 182 km — E/W half-extent of box
BOX_AREA_KM2 = meta["box_area_km2"]   # ≈ 161 000 km²
T_DAYS       = meta["t_days"]         # catalog window length = 30 days
MC           = meta["mc"]             # magnitude of completeness = 3.6
MAG_MAX      = meta["mag_max"]        # 8.0 — upper bound for ContinuousMarks
N_CATALOGS   = meta["n_catalogs"]     # 300

# True ETAS parameters in RECAST-comparable units (pre-computed in generation script).
# We print these at the end alongside RECAST's fitted values.
TRUE_P     = meta["recast_p_true"]       # Omori p = 1 + omega
TRUE_C     = meta["recast_c_true"]       # Omori c [days]
TRUE_ALPHA = meta["recast_alpha_true"]   # = a in etas_2 = alpha in RECAST
TRUE_MU    = meta["recast_mu_rate_true"] # background rate [events/day] over the box

MIN_EVENTS = 3   # drop catalogs with fewer events than this (too sparse to train on)

print(f"Loaded metadata from {DATA_DIR}true_params.json")
print(f"  True p={TRUE_P:.2f}  c={TRUE_C:.5f} d  alpha={TRUE_ALPHA:.2f}")
print(f"  True mu={TRUE_MU:.3f} events/day (over {BOX_AREA_KM2:.0f} km²)")
print(f"  T_DAYS={T_DAYS}  MC={MC}  MAG_MAX={MAG_MAX}")


#%%
# ─── Section 2: Load parquet and convert to RECAST Sequences ──────────────────
#
# etas_2 outputs a DataFrame with columns:
#     catalog_id, latitude [°N], longitude [°W], time [datetime], magnitude
#
# RECAST needs a Sequence object with:
#     inter_times  — time gaps between consecutive events [days]; shape (n+1,)
#                    inter_times[0]  = gap from window start (0.0) to first event
#                    inter_times[-1] = gap from last event to window end (T_DAYS)
#     t_start      — 0.0 (we define each window start as time zero)
#     mag          — ContinuousMarks object wrapping a (n,) float32 tensor
#     x_loc        — km east  of polygon centroid; shape (n,) float32
#     y_loc        — km north of polygon centroid; shape (n,) float32
#
# Coordinate projection:
#     x_km = (longitude − LON_CTR) × KM_PER_LON     east is positive
#     y_km = (latitude  − LAT_CTR) × KM_PER_LAT     north is positive
#
# This is the same flat-Earth (equirectangular) projection used in
# test_case_study.py:load_mainshock_sequence().  It's accurate to ~0.1% over
# the ~400 km extent of our box.

def catalog_to_sequence(df_group):
    """Convert one etas_2 catalog (a sub-DataFrame) to a RECAST Sequence.

    Args:
        df_group: DataFrame rows for a single catalog_id.
                  Expected columns: latitude, longitude, time, magnitude.

    Returns:
        eq.data.Sequence  with inter_times, mag (ContinuousMarks), x_loc, y_loc.
        None if the group has fewer than MIN_EVENTS events.
    """
    # Sort by time (etas_2 may not guarantee order when aftershock generations merge)
    df = df_group.sort_values("time").reset_index(drop=True)
    df = df[df.magnitude >= MC].reset_index(drop=True)

    if len(df) < MIN_EVENTS:
        return None

    # ── Project geographic coordinates to km offsets from the polygon centroid ─
    # "East" and "North" here match the convention in test_case_study.py so that
    # models trained on different datasets share the same spatial semantics.
    x_km = ((df.longitude.values - LON_CTR) * KM_PER_LON).astype(np.float32)
    y_km = ((df.latitude.values  - LAT_CTR) * KM_PER_LAT).astype(np.float32)

    # ── Convert datetime → fractional days since window start ─────────────────
    # Each catalog was generated over a T_DAYS-day window.  We measure time
    # from the window start (t_start = 0.0).  All etas_2 events fall strictly
    # in the open interval (0, T_DAYS), so the first and last inter-times are > 0.
    t_window_start = df["time"].iloc[0].replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    # Round window start to nearest day boundary — etas_2 guarantees events are
    # in (window_start, window_end) so the exact value doesn't affect relative times.
    arrival_days = (df["time"] - t_window_start).dt.total_seconds().values / 86400.0
    # Safety clip: keep all arrivals strictly inside (0, T_DAYS) to avoid
    # zero or negative inter-times at floating-point boundaries.
    arrival_days = np.clip(arrival_days, 1e-6, T_DAYS - 1e-6)

    # inter_times[0]   = arrival_days[0] − 0.0          (gap from window start)
    # inter_times[i]   = arrival_days[i] − arrival_days[i-1]   (event to event)
    # inter_times[-1]  = T_DAYS − arrival_days[-1]       (gap to window end)
    inter_times = np.diff(arrival_days, prepend=[0.0], append=[float(T_DAYS)])

    # ── Wrap magnitudes in ContinuousMarks ─────────────────────────────────────
    # ContinuousMarks stores: the raw magnitude values + (mc, mag_max) bounds
    # used by RecurrentTPP to compute the Gutenberg-Richter log-probability.
    # The ETAS model ignores the bounds and reads only the raw .values tensor.
    mag = eq.data.ContinuousMarks(
        df.magnitude.values.astype(np.float32),
        bounds     = [MC, MAG_MAX],
        nll_bounds = [MC, MAG_MAX],
    )

    return eq.data.Sequence(
        inter_times,
        t_start = 0.0,     # all sequences start at t=0 (window start)
        mag     = mag,
        x_loc   = torch.tensor(x_km),
        y_loc   = torch.tensor(y_km),
    )


raw_df = pd.read_parquet(f"{DATA_DIR}raw_catalogs.parquet")
print(f"Loaded {len(raw_df):,} events from {raw_df.catalog_id.nunique()} catalogs")

# Convert every catalog group to a Sequence (or None if too sparse)
sequences = []
for cat_id, group in raw_df.groupby("catalog_id"):
    seq = catalog_to_sequence(group)
    if seq is not None:
        sequences.append(seq)

print(f"Sequences after ≥{MIN_EVENTS}-event filter: {len(sequences)} / {N_CATALOGS}")

# ── Train / val / test split (60 / 20 / 20) ────────────────────────────────────
# We split by index (not by time) because each catalog is an independent
# realisation — there is no temporal ordering between catalogs to preserve.
n_total = len(sequences)
n_train = int(0.60 * n_total)
n_val   = int(0.20 * n_total)

train_seqs = sequences[:n_train]
val_seqs   = sequences[n_train : n_train + n_val]
test_seqs  = sequences[n_train + n_val :]

train_ds = eq.data.InMemoryDataset(train_seqs)
val_ds   = eq.data.InMemoryDataset(val_seqs)
test_ds  = eq.data.InMemoryDataset(test_seqs)

print(f"Split: {len(train_ds)} train / {len(val_ds)} val / {len(test_ds)} test")

# Quick sanity check on the first training sequence
s0 = train_ds[0]
print(f"\nFirst training sequence:")
print(f"  Events   : {s0.num_events}")
print(f"  Duration : {s0.t_end:.2f} days (should be ≈{T_DAYS})")
print(f"  x range  : [{s0.x_loc.min():.1f}, {s0.x_loc.max():.1f}] km")
print(f"  y range  : [{s0.y_loc.min():.1f}, {s0.y_loc.max():.1f}] km")
print(f"  mag range: [{s0.mag.numpy().min():.1f}, {s0.mag.numpy().max():.1f}]")


#%%
# ─── Section 3: Normalization statistics ───────────────────────────────────────
# RecurrentTPP encodes events as:
#   time  → log(τ) − log(τ_mean)          (log inter-time, zero-centred)
#   space → (x − x_mean) / x_std,  same for y
#   mag   → (m − Mc)                       (no normalisation needed; already ≥ 0)
#
# We compute τ_mean, x_mean, x_std, y_mean, y_std from the TRAINING set only
# and register them as fixed buffers in the model.  Applying them to val/test
# sequences is valid because ETAS is stationary: the population statistics are
# the same everywhere in the box and across all time windows.
#
# Unlike test_case_study.py we do NOT inflate the std by a jitter term because
# we apply no spatial jitter here (explained in Section 5 below).

all_x   = np.concatenate([s.x_loc.numpy() for s in train_ds])
all_y   = np.concatenate([s.y_loc.numpy() for s in train_ds])
all_tau = np.concatenate([s.inter_times[:-1].numpy() for s in train_ds])

# x_mean ≈ 0, y_mean ≈ 0 because etas_2 uses a uniform background and the
# box is centred on (LAT_CTR, LON_CTR).  We set them explicitly to 0 rather
# than estimating them to avoid fitting noise.
x_mean, y_mean = 0.0, 0.0
x_std    = float(all_x.std())
y_std    = float(all_y.std())
tau_mean = float(all_tau.mean())

print(f"Normalization (from {len(train_ds)} training sequences):")
print(f"  tau_mean = {tau_mean:.4f} days")
print(f"  x_std    = {x_std:.1f} km")
print(f"  y_std    = {y_std:.1f} km")


#%%
# ─── Section 4: Quick EDA — plot the first test sequence ──────────────────────
# Visual sanity check before training.  A healthy etas_2 sequence should show:
#   Left:  magnitude-time plot with possible aftershock bursts after large events
#   Right: spatial scatter with mild clustering (aftershocks near their parents)

seq_ref = test_seqs[0]   # "reference" sequence — reused in Sections 6, 7, 8

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

# M-t plot: each vertical bar = one event, height = magnitude
axes[0].stem(
    seq_ref.arrival_times.numpy(), seq_ref.mag.numpy(),
    linefmt='grey', markerfmt='o', basefmt=' '
)
axes[0].set_xlabel("Days in window")
axes[0].set_ylabel("Magnitude")
axes[0].set_title(f"Reference test sequence — {seq_ref.num_events} events")

# Spatial scatter: colour = arrival time (early = dark, late = bright)
sc = axes[1].scatter(
    seq_ref.x_loc.numpy(), seq_ref.y_loc.numpy(),
    s   = (seq_ref.mag.numpy() - MC + 0.5) ** 2 * 8,   # marker size ∝ magnitude
    c   = seq_ref.arrival_times.numpy(),
    cmap='viridis', alpha=0.7,
)
axes[1].axhline(0, color='k', lw=0.5, ls='--')
axes[1].axvline(0, color='k', lw=0.5, ls='--')
axes[1].set_xlabel("East of box center (km)")
axes[1].set_ylabel("North of box center (km)")
axes[1].set_title("Spatial distribution — colour = arrival time")
axes[1].set_xlim(-HALF_KM_LON * 1.05, HALF_KM_LON * 1.05)
axes[1].set_ylim(-HALF_KM_LAT * 1.05, HALF_KM_LAT * 1.05)
plt.colorbar(sc, ax=axes[1], label="Days")
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/eda_reference_sequence.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 5: Fit RECAST's ETAS model — temporal NLL baseline ───────────────
#
# Before training RecurrentTPP we fit RECAST's built-in parametric ETAS model
# to the same training sequences.  This gives us:
#   (a) A BASELINE NLL that RecurrentTPP should eventually beat (or match).
#   (b) A PARAMETER RECOVERY check: do the fitted p, c, alpha, mu match the
#       true values used in data generation?
#
# IMPORTANT NLL CAVEAT:
#   ETAS(use_spatial=False).nll_loss() returns only the TEMPORAL NLL per day
#   (log-intensity of inter-event times + compensator integral).
#   RecurrentTPP.nll_loss() returns TEMPORAL + 0.1×SPATIAL + MAGNITUDE NLL.
#   These are NOT identical quantities, so the numerical comparison is
#   approximate.  The magnitude term is the same GR distribution for both, but
#   ETAS scores it analytically (as part of the compensator) while RecurrentTPP
#   scores it via the GR hypernet.  The 0.1 weight on the spatial term keeps
#   the temporal component dominant in RECAST's NLL.
#
# We use use_spatial=False here to isolate the temporal component and keep the
# comparison as direct as possible.  (The spatial ETAS — use_spatial=True —
# was implemented in eq/models/etas.py but is a separate experiment.)

etas_baseline = ETAS(
    mag_completeness         = MC,
    richter_b                = 1.0,
    use_spatial              = False,   # temporal-only; see caveat above
    # Initialise near the true values so the optimizer doesn't wander far.
    # This is not necessary but speeds up convergence.
    omori_p_init             = TRUE_P,
    omori_c_init             = TRUE_C,
    productivity_alpha_init  = TRUE_ALPHA,
    base_rate_init           = max(TRUE_MU, 0.01),   # must be > 0 for log-space init
    report_params            = False,
    learning_rate            = 5e-2,
)

# ── Manual training loop (no Lightning) ────────────────────────────────────────
# Full-batch gradient descent: all training sequences in one batch.
# This is fine because N_train ≈ 180 sequences × 30 days is small.
train_batch_etas = eq.data.Batch.from_list(train_seqs)
etas_optimizer   = torch.optim.Adam(etas_baseline.parameters(), lr=5e-2)

ETAS_EPOCHS = 600
etas_losses = []

print(f"Training ETAS baseline for {ETAS_EPOCHS} epochs...")
etas_baseline.train()
for epoch in range(ETAS_EPOCHS):
    etas_optimizer.zero_grad()
    # nll_loss returns one scalar per sequence; we average across the batch.
    nll = etas_baseline.nll_loss(train_batch_etas).mean()
    nll.backward()
    # Gradient clipping prevents log-space parameters from exploding early on.
    torch.nn.utils.clip_grad_norm_(etas_baseline.parameters(), 1.0)
    etas_optimizer.step()
    etas_losses.append(nll.item())

    if (epoch + 1) % 100 == 0:
        print(f"  Epoch {epoch+1:4d}  NLL={nll.item():.4f}  "
              f"p={etas_baseline.p.item():.3f}  "
              f"c={etas_baseline.c.item():.5f}  "
              f"mu={etas_baseline.mu.item():.4f}  "
              f"alpha={etas_baseline.alpha.item():.3f}")

etas_baseline.eval()

fig, ax = plt.subplots(figsize=(8, 3))
ax.plot(etas_losses, linewidth=0.8, color='darkorange')
ax.set_xlabel("Epoch")
ax.set_ylabel("Mean NLL / day")
ax.set_title("ETAS baseline training loss")
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/etas_training_loss.png", dpi=150, bbox_inches='tight')
plt.show()

# ── Parameter recovery table ────────────────────────────────────────────────────
print("\nParameter recovery (True vs. ETAS-fitted):")
print(f"  {'Parameter':12s}  {'True':>10s}  {'Fitted':>10s}  Note")
print(f"  {'-'*12}  {'-'*10}  {'-'*10}  {'-'*30}")
print(f"  {'p':12s}  {TRUE_P:>10.3f}  "
      f"{etas_baseline.p.item():>10.3f}  Omori decay exponent")
print(f"  {'c (days)':12s}  {TRUE_C:>10.5f}  "
      f"{etas_baseline.c.item():>10.5f}  Omori time offset")
print(f"  {'alpha':12s}  {TRUE_ALPHA:>10.3f}  "
      f"{etas_baseline.alpha.item():>10.3f}  Productivity magnitude scaling")
print(f"  {'mu (ev/day)':12s}  {TRUE_MU:>10.4f}  "
      f"{etas_baseline.mu.item():>10.4f}  Background rate (total, box area)")
print("  Note: k is not directly comparable (different Omori normalizations).")

# ── ETAS test NLL (the baseline to beat) ────────────────────────────────────────
test_batch = eq.data.Batch.from_list(test_seqs)
with torch.no_grad():
    etas_test_nll = etas_baseline.nll_loss(test_batch).mean().item()
print(f"\nETAS temporal NLL on test set: {etas_test_nll:.4f} per day")


#%%
# ─── Section 6: Define and train RecurrentTPP ─────────────────────────────────
#
# Architecture (from eq/models/recurrent.py):
#   Encoder: each event → [log(τ) − log(τ_mean), (x−x_mean)/x_std,
#                           (y−y_mean)/y_std, (m−Mc)]  — a 4-dimensional vector
#   RNN (GRU): encodes event history → context vector of size context_size
#   Decoders (hypernets):
#     hypernet_time → Weibull mixture parameters (num_components_time components)
#     hypernet_xy   → 2D Gaussian mixture parameters with Cholesky covariance
#     hypernet_mag  → Gutenberg-Richter parameters (effectively learns b-value)
#
# NLL loss returned per sequence per day:
#   − [log p(inter_times) + 0.1 × log p(x_loc, y_loc) + log S(t_last)
#      − log S(t_first)  − log p(magnitudes)]  /  (t_end − t_nll_start)
#
# The 0.1 spatial weight means the model is primarily a temporal forecaster;
# spatial structure is a secondary objective.
#
# MODEL SIZE: We use a smaller model than test_case_study.py (context_size=64
# vs 256) because the synthetic sequences are shorter (30 vs 365 days) and
# the ETAS dynamics are simpler than real multi-sequence global seismicity.

model = eq.models.RecurrentTPP(
    context_size         = 64,    # RNN hidden-state dimension
    num_components_time  = 8,     # Weibull mixture components for time
    num_components_space = 16,    # Gaussian mixture components for space
    tau_mean             = tau_mean,
    x_mean               = x_mean,
    y_mean               = y_mean,
    x_std                = x_std,
    y_std                = y_std,
)
print(f"RecurrentTPP parameters: {sum(p.numel() for p in model.parameters()):,}")

# ── Training configuration ──────────────────────────────────────────────────────
_RETRAIN_   = True   # set False to skip training and just load the saved checkpoint
EPOCHS      = 300
BATCH_SIZE  = 32

# SPATIAL JITTER NOTE:
#   test_case_study.py applies random spatial translation per sequence during
#   training (collate_with_jitter).  This prevents the model from memorising
#   the mainshock's absolute position (always at origin) as a spatial prior.
#
#   We do NOT apply jitter here because:
#   (a) There is no mainshock — events are scattered across the box uniformly.
#   (b) The ETAS background is spatially uniform; the model should NOT need to
#       learn any preferred absolute location.
#   (c) Adding jitter would widen the apparent spatial distribution and inflate
#       x_std / y_std beyond the true box extent, making normalization wrong.
#
#   Plain Batch.from_list() is therefore the correct collate function.

if _RETRAIN_:
    device    = 'cuda' if torch.cuda.is_available() else 'cpu'
    model     = model.to(device)
    print(f"Training RecurrentTPP on: {device}")

    optimizer    = torch.optim.Adam(model.parameters(), lr=5e-4)
    scheduler    = CosineAnnealingLR(optimizer, T_max=EPOCHS)
    train_loader = DataLoader(
        train_ds,
        batch_size  = BATCH_SIZE,
        shuffle     = True,
        collate_fn  = eq.data.Batch.from_list,   # no jitter (see note above)
    )
    val_batch = eq.data.Batch.from_list(val_seqs).to(device)

    train_losses, val_losses = [], []
    model.train()
    for epoch in range(EPOCHS):
        epoch_losses = []
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            nll = model.nll_loss(batch).mean()
            nll.backward()
            # Clip gradients to prevent parameter explosions (especially early on
            # when the context vectors are near-random and spatial NLL can spike).
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_losses.append(nll.item())

        # Validation NLL — computed without gradients on the full validation set.
        with torch.no_grad():
            v_nll = model.nll_loss(val_batch).mean().item()

        epoch_mean = float(np.mean(epoch_losses))
        train_losses.append(epoch_mean)
        val_losses.append(v_nll)
        scheduler.step()

        if (epoch + 1) % 25 == 0:
            print(f"Epoch {epoch+1:3d}  train={epoch_mean:.4f}  val={v_nll:.4f}")

    torch.save(model.state_dict(), f"{SAVE_DIR}/recast_etas2.pt")

    fig, ax = plt.subplots(figsize=(9, 3))
    ax.plot(train_losses, label='train', color='steelblue', lw=0.9)
    ax.plot(val_losses,   label='val',   color='orange',    lw=0.9)
    ax.axhline(etas_test_nll, ls='--', color='red', lw=1.2, label='ETAS temporal NLL')
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Mean NLL / day")
    ax.set_title("RecurrentTPP training loss  (dashed = ETAS temporal baseline)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/recast_training_loss.png", dpi=150, bbox_inches='tight')
    plt.show()


#%%
# ─── Section 7: Load trained model ────────────────────────────────────────────
map_location = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.cpu()
model.load_state_dict(torch.load(f"{SAVE_DIR}/recast_etas2.pt",
                                  map_location='cpu'))
model.eval()
print(f"Loaded checkpoint from {SAVE_DIR}/recast_etas2.pt")


#%%
# ─── Section 8: NLL comparison table ──────────────────────────────────────────
# Evaluate both models on the held-out test set and print a comparison.
# Reminder: the NLLs include different components (see Section 5 caveat),
# so treat this as an approximate comparison.

with torch.no_grad():
    recast_test_nll = model.nll_loss(test_batch).mean().item()

print("\n" + "="*55)
print(f"  {'Model':30s}  {'NLL / day':>10s}")
print(f"  {'-'*30}  {'-'*10}")
print(f"  {'ETAS (temporal only)':30s}  {etas_test_nll:>10.4f}")
print(f"  {'RecurrentTPP (temporal+spatial)':30s}  {recast_test_nll:>10.4f}")
print("="*55)
print("  Note: RECAST NLL includes 0.1×spatial + magnitude terms.")
print("  Lower = better at predicting held-out sequences.")


#%%
# ─── Section 9: Cumulative count forecast — ETAS vs. RECAST ──────────────────
# We condition both models on the FIRST HALF of the reference test sequence
# and ask each to forecast the SECOND HALF.
#
# Visualisation: 100 sampled trajectories → q10/q25/q75/q90 quantile bands
# overlaid with the observed cumulative count step function.
#
# This tests whether the neural model captures the Omori-like decay in rates
# after a burst — a key signature of ETAS that RECAST should learn.

FORECAST_BATCH = 200   # number of Monte Carlo trajectories per model

# Split the reference sequence at the midpoint (T_DAYS / 2 = 15 days)
condition_days = T_DAYS / 2.0
forecast_days  = float(seq_ref.t_end) - condition_days
cond_seq = seq_ref.get_subsequence(seq_ref.t_start, condition_days)
print(f"Reference sequence: {seq_ref.num_events} total events")
print(f"  Conditioning on  t ∈ [0, {condition_days:.0f}) days  "
      f"({cond_seq.num_events} events)")
print(f"  Forecasting      t ∈ [{condition_days:.0f}, {seq_ref.t_end:.0f}] days")


def forecast_cumulative(batch, t_cut, t_grid):
    """Cumulative event count relative to t_cut for each sampled trajectory.

    Args:
        batch   : Batch of sampled sequences from model.sample().
        t_cut   : The conditioning cutoff time (events before this are history).
        t_grid  : 1-D array of times at which to evaluate the cumulative count.

    Returns:
        cum: int array of shape (batch_size, len(t_grid)).
             cum[i, j] = number of events in trajectory i with arrival_time
             in (t_cut, t_cut + t_grid[j]].
    """
    cum = np.zeros((batch.batch_size, len(t_grid)), dtype=int)
    for i in range(batch.batch_size):
        mask      = batch.mask[i].bool()
        times     = batch.arrival_times[i][~mask].numpy()
        # Only count events strictly after the conditioning cutoff
        fore_rel  = np.sort(times[times > t_cut] - t_cut)
        cum[i]    = np.searchsorted(fore_rel, t_grid, side='right')
    return cum


T_SHOW = float(forecast_days)
N_GRID = 300
t_grid = np.linspace(0, T_SHOW, N_GRID)

# Observed cumulative count in the forecast window
obs_times_rel = seq_ref.arrival_times.numpy() - condition_days
obs_fore      = np.sort(obs_times_rel[obs_times_rel > 0])
obs_cum       = np.searchsorted(obs_fore, t_grid, side='right')

# ── ETAS forecast (temporal model, samples without spatial locations) ─────────
print("Sampling ETAS trajectories...")
etas_baseline.eval()
with torch.no_grad():
    etas_pred = etas_baseline.sample(
        batch_size  = FORECAST_BATCH,
        duration    = forecast_days,
        t_start     = condition_days,
        past_seq    = cond_seq,
        random_state = 10,
        n_jobs      = 1,   # single-process to avoid pickling issues
    )
etas_cum = forecast_cumulative(etas_pred, condition_days, t_grid)
e_q10, e_q25, e_q75, e_q90 = np.percentile(etas_cum, [10, 25, 75, 90], axis=0)

# ── RECAST forecast ────────────────────────────────────────────────────────────
print("Sampling RECAST trajectories...")
model.eval()
with torch.no_grad():
    recast_pred = model.sample(
        batch_size       = FORECAST_BATCH,
        duration         = forecast_days,
        t_start          = condition_days,
        past_seq         = cond_seq,
        mag_completeness = MC,
    )
recast_cum = forecast_cumulative(recast_pred, condition_days, t_grid)
r_q10, r_q25, r_q75, r_q90 = np.percentile(recast_cum, [10, 25, 75, 90], axis=0)

# ── Plot ────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4), sharey=True)
fig.suptitle("Cumulative count forecast — conditioning on first half of reference sequence",
             fontsize=11)

for ax, cum_q10, cum_q25, cum_q75, cum_q90, color, label in [
    (axes[0], e_q10, e_q25, e_q75, e_q90, 'darkorange', 'ETAS (parametric)'),
    (axes[1], r_q10, r_q25, r_q75, r_q90, 'steelblue',  'RecurrentTPP (neural)'),
]:
    # Shaded bands: q10–q90 (outer, translucent) and q25–q75 (inner, denser)
    ax.fill_between(t_grid, cum_q10, cum_q90, alpha=0.20, color=color)
    ax.fill_between(t_grid, cum_q25, cum_q75, alpha=0.45, color=color)
    # Observed step function
    ax.step(np.concatenate([[0], t_grid]),
            np.concatenate([[0], obs_cum]),
            where='post', color='k', linewidth=1.8, label='Observed', zorder=5)
    ax.set_xlabel("Days after conditioning cutoff")
    ax.set_ylabel("Cumulative events")
    ax.set_title(label)
    ax.legend(fontsize=9)
    ax.set_xlim(0, T_SHOW)
    ax.set_ylim(bottom=0)

plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/forecast_cumulative.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 10: Inter-event time distributions ───────────────────────────────
# Compare the inter-event time density learned by RECAST against the empirical
# histogram from all training sequences.
#
# RECAST's time decoder is a Weibull mixture (plot_time_mixture from
# plot_helpers.py).  We show two contexts:
#   Left:  zero context — the model's "prior" before seeing any events.
#          Should match the average inter-event distribution from training.
#   Right: context after conditioning on the reference sequence (first half).
#          Should show shorter inter-times if a burst just occurred (Omori effect).

# Aggregate inter-event times from 50 training sequences for the histogram
training_inter = np.concatenate([
    train_ds[i].inter_times[:-1].numpy()
    for i in range(min(50, len(train_ds)))
])

# Inter-event times after the conditioning cutoff from the reference sequence
post_cond_inter = cond_seq.inter_times[:-1].numpy()
# Also grab post-condition events from seq_ref for a richer histogram
post_ref = seq_ref.get_subsequence(condition_days, seq_ref.t_end)
post_ref_inter = post_ref.inter_times[:-1].numpy() if post_ref.num_events > 0 else np.array([])

# Context vectors
context_zero = torch.zeros(1, 1, model.context_size)
cond_batch   = eq.data.Batch.from_list([cond_seq])
with torch.no_grad():
    context_cond = model.get_context(cond_batch)[:, [-1], :]   # last context vector

T_MAX = 5.0   # x-axis limit for the density plot [days]
Y_MAX = 40    # y-axis limit for density

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

for ax, ctx, title, obs_inter, obs_label in [
    (axes[0], context_zero, 'Prior (zero context)',
     training_inter, f"Training sequences (50 of {len(train_ds)})"),
    (axes[1], context_cond,
     f'After conditioning ({cond_seq.num_events} events, t=0–{condition_days:.0f} d)',
     post_ref_inter, "Reference seq (post-condition)"),
]:
    plot_time_mixture(model, ctx, ax, t_max=T_MAX)
    if len(obs_inter) > 0:
        # Log-spaced bins to show the long tail
        bins = np.logspace(-3, np.log10(T_MAX * 3), 60)
        ax.hist(obs_inter, bins=bins, density=True,
                alpha=0.35, color='red', rwidth=0.9, label=obs_label)
    ax.set_xlabel("Inter-event time (days)")
    ax.set_ylabel("Density")
    ax.set_xlim([0, T_MAX * 0.5])
    ax.set_ylim([0, Y_MAX])
    ax.set_title(title)
    ax.legend(fontsize=8)

plt.suptitle("Weibull inter-event time mixture — RECAST", fontsize=12)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/time_mixture.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 11: Spatial Gaussian mixture — prior vs. conditioned ─────────────
# Visualise the spatial distribution learned by RECAST's hypernet_xy.
#   Left:  zero-context prior — should be a diffuse distribution covering
#          roughly the extent of the training box.
#   Right: conditioned on the first half of the reference sequence — may show
#          tighter clusters around recently active regions if the model has
#          learned the aftershock kernel.

TAU_VIZ = 0.5   # [days] — inter-time shown to the spatial decoder.
                 # Small τ emphasises the near-source zone; large τ gives background.

fig, axes = plt.subplots(1, 2, figsize=(13, 6))

for ax, ctx, title in [
    (axes[0], context_zero, 'Spatial prior  (zero context)'),
    (axes[1], context_cond, f'After conditioning  ({cond_seq.num_events} events)'),
]:
    # A few training sequences in grey for scale
    for i in range(min(8, len(train_ds))):
        s = train_ds[i]
        ax.scatter(s.x_loc.numpy(), s.y_loc.numpy(), s=2, alpha=0.12, c='grey', zorder=1)

    plot_xy_mixture(model, ctx, ax, alpha=0.06, tau=TAU_VIZ)

    # Box boundary dashes
    ax.axhline(0, color='k', lw=0.5, ls='--')
    ax.axvline(0, color='k', lw=0.5, ls='--')
    ax.set_xlim(-HALF_KM_LON * 1.05, HALF_KM_LON * 1.05)
    ax.set_ylim(-HALF_KM_LAT * 1.05, HALF_KM_LAT * 1.05)
    ax.set_xlabel("East of box center (km)")
    ax.set_ylabel("North of box center (km)")
    ax.set_title(title)

# Overlay reference events on the conditioned panel
axes[1].scatter(
    seq_ref.x_loc.numpy(), seq_ref.y_loc.numpy(),
    s=(seq_ref.mag.numpy() - MC + 0.5) ** 2 * 8,
    c='dodgerblue', alpha=0.7, edgecolors='k', linewidths=0.3,
    zorder=5, label=f'Reference seq (M≥{MC})'
)
axes[1].legend(fontsize=8)

plt.suptitle(f"Spatial Gaussian mixture  |  τ = {TAU_VIZ} days", fontsize=12)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/spatial_mixture.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 12: Spatial forecast — expected event count grid ─────────────────
# Sample RECAST trajectories and bin forecast events into a 2-D grid.
# The expected count per cell (total events / trajectories) visualises where
# the model predicts seismicity to concentrate over the forecast window.

NX, NY = 30, 30

x_bins = np.linspace(-HALF_KM_LON, HALF_KM_LON, NX + 1)
y_bins = np.linspace(-HALF_KM_LAT, HALF_KM_LAT, NY + 1)

all_x, all_y, all_m = [], [], []
for i in range(recast_pred.batch_size):
    mask = recast_pred.mask[i].bool()
    all_x.append(recast_pred.x_loc[i][~mask].numpy())
    all_y.append(recast_pred.y_loc[i][~mask].numpy())
    all_m.append(recast_pred.mag[i][~mask].numpy())

all_x = np.concatenate(all_x)
all_y = np.concatenate(all_y)
all_m = np.concatenate(all_m)

# Only count events inside the grid domain (avoids edge inflation from digitize)
in_domain = (
    (all_x >= x_bins[0]) & (all_x < x_bins[-1]) &
    (all_y >= y_bins[0]) & (all_y < y_bins[-1])
)
all_x, all_y, all_m = all_x[in_domain], all_y[in_domain], all_m[in_domain]

ix = np.digitize(all_x, x_bins) - 1
iy = np.digitize(all_y, y_bins) - 1

count_grid = np.zeros((NX, NY))
for ci in range(NX):
    for cj in range(NY):
        sel = (ix == ci) & (iy == cj)
        count_grid[ci, cj] = sel.sum() / recast_pred.batch_size

count_grid = np.where(count_grid > 0, count_grid, np.nan)
extent = [x_bins[0], x_bins[-1], y_bins[0], y_bins[-1]]

fig, ax = plt.subplots(figsize=(7, 7))
cmap = plt.cm.Blues.copy()
cmap.set_bad('lightgrey')
im = ax.imshow(
    count_grid.T, origin='lower', extent=extent, aspect='auto', cmap=cmap
)
plt.colorbar(im, ax=ax, label="Expected events / cell")
# Observed reference events (condition = orange, forecast window = blue)
cond_mask = seq_ref.arrival_times.numpy() <= condition_days
ax.scatter(seq_ref.x_loc.numpy()[cond_mask],  seq_ref.y_loc.numpy()[cond_mask],
           s=8, color='orange', alpha=0.8, label='Observed (conditioning)')
ax.scatter(seq_ref.x_loc.numpy()[~cond_mask], seq_ref.y_loc.numpy()[~cond_mask],
           s=8, color='red',    alpha=0.8, label='Observed (forecast window)')
ax.axhline(0, color='w', lw=0.5, ls='--')
ax.axvline(0, color='w', lw=0.5, ls='--')
ax.set_xlabel("East of box center (km)")
ax.set_ylabel("North of box center (km)")
ax.set_title(f"RECAST expected event count\n(conditioning: first {condition_days:.0f} d, "
             f"forecast: last {forecast_days:.0f} d)")
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/spatial_forecast_grid.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 13: Data quantity sweep ──────────────────────────────────────────
# Key research question: how much data does RecurrentTPP need to match ETAS?
#
# For each N in N_TRAIN_SIZES we:
#   1. Take the first N sequences from the training set.
#   2. Train a fresh RecurrentTPP for SWEEP_EPOCHS epochs.
#   3. Evaluate its NLL on the full test set.
#
# The ETAS baseline NLL (from Section 5) is shown as a dashed horizontal line.
# When the RECAST curve crosses below this line, RECAST has exceeded the
# parametric model's predictive accuracy.
#
# NOTE: SWEEP_EPOCHS is intentionally short (50 epochs) so each point can be
# trained in seconds.  The NLLs therefore reflect early-convergence performance,
# not the fully-trained model.  Increase SWEEP_EPOCHS for a more accurate sweep
# at the cost of longer runtime.

N_TRAIN_SIZES = [5, 10, 25, 50, 100, len(train_seqs)]
SWEEP_EPOCHS  = 50

sweep_nlls = []
print(f"\nData quantity sweep  ({len(N_TRAIN_SIZES)} points × {SWEEP_EPOCHS} epochs each)")

for n_train in N_TRAIN_SIZES:
    # Fresh model with the same architecture every time (no warm-start)
    m_sweep = eq.models.RecurrentTPP(
        context_size         = 64,
        num_components_time  = 8,
        num_components_space = 16,
        tau_mean             = tau_mean,
        x_mean               = x_mean,
        y_mean               = y_mean,
        x_std                = x_std,
        y_std                = y_std,
    )
    opt_sweep = torch.optim.Adam(m_sweep.parameters(), lr=5e-4)

    # Build a DataLoader from the first n_train sequences
    subset_ds     = eq.data.InMemoryDataset(train_seqs[:n_train])
    loader_sweep  = DataLoader(
        subset_ds,
        batch_size = min(32, n_train),    # smaller batch when n_train is tiny
        shuffle    = True,
        collate_fn = eq.data.Batch.from_list,
    )

    m_sweep.train()
    for _ in range(SWEEP_EPOCHS):
        for batch in loader_sweep:
            opt_sweep.zero_grad()
            model.nll_loss(batch).mean().backward() if False else \
            m_sweep.nll_loss(batch).mean().backward()
            torch.nn.utils.clip_grad_norm_(m_sweep.parameters(), 1.0)
            opt_sweep.step()

    m_sweep.eval()
    with torch.no_grad():
        nll_sweep = m_sweep.nll_loss(test_batch).mean().item()
    sweep_nlls.append(nll_sweep)
    print(f"  N_train={n_train:4d}  test NLL={nll_sweep:.4f}")

# ── Plot ────────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 4))
ax.semilogx(N_TRAIN_SIZES, sweep_nlls, 'o-', color='steelblue',
            linewidth=1.5, markersize=6, label='RecurrentTPP')
ax.axhline(etas_test_nll, ls='--', color='darkorange', lw=1.5,
           label=f'ETAS baseline  ({etas_test_nll:.4f})')
ax.set_xlabel("Number of training sequences  (log scale)")
ax.set_ylabel("Test NLL / day")
ax.set_title(f"Data quantity sweep  ({SWEEP_EPOCHS} epochs each)\n"
             "How much data does RECAST need to match ETAS?")
ax.legend()
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/data_quantity_sweep.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"\nETAS baseline NLL : {etas_test_nll:.4f}")
print(f"RECAST (full data): {sweep_nlls[-1]:.4f}")
crossover = [n for n, nll in zip(N_TRAIN_SIZES, sweep_nlls) if nll <= etas_test_nll]
if crossover:
    print(f"RECAST first beats ETAS at N_train ≥ {crossover[0]}")
else:
    print("RECAST does not yet beat ETAS with these training sizes / epoch budget.")
    print("Try increasing SWEEP_EPOCHS or N_CATALOGS in generate_etas_synthetic.py.")

# %%
