#%%
"""
test_replicate_ETAS.py
======================
Trains RECAST's RecurrentTPP on synthetic ETAS catalogs (generated by
generate_etas_synthetic.py) and evaluates how faithfully the neural model
replicates the generative process.

WHAT THIS TESTS:
    - Can a neural temporal point process (RecurrentTPP) recover the statistics
      of a known parametric model (ETAS)?
    - How much data does RecurrentTPP need before it matches ETAS's NLL on
      held-out sequences?  (Section 9: data quantity sweep)

WORKFLOW:
    1. Load etas_2 synthetic catalogs from parquet + metadata JSON.
    2. Project each catalog's lat/lon events into local km coordinates and
       build RECAST Sequence objects.
    3. Split into train / val / test (60 / 20 / 20).
    4. Fit RECAST's built-in ETAS model to training sequences — gives a
       parametric baseline NLL and a parameter recovery check.
    5. Train RecurrentTPP on the same sequences.
    6. Compare: NLL table, cumulative forecast bands, inter-event time mixture,
       spatial intensity map.
    7. Data quantity sweep: retrain with progressively fewer sequences to find
       the crossover point where RECAST beats ETAS.

PREREQUISITE:
    Run generate_etas_synthetic.py first to create:
        case_studies/etas2_synthetic/raw_catalogs.parquet
        case_studies/etas2_synthetic/true_params.json
"""

import json
import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader

torch.set_num_threads(1)   # prevents PyTorch from spawning extra threads on CPU

import eq
from eq.models.etas import ETAS
from plot_helpers import plot_time_mixture, plot_xy_mixture

# ── Spatial distribution toggle ─────────────────────────────────────────────
# 'gaussian' (default, matches original behavior) or 'student_t' (heavier
# tails — see spatial_dist/spatial_df args on eq.models.RecurrentTPP). Same
# hypernet_xy architecture either way; switch back by changing this one line.
SPATIAL_DIST = "student_t"   # 'gaussian' or 'student_t'
SPATIAL_DF   = 4.0          # degrees of freedom; only used if SPATIAL_DIST == 'student_t'

# ── Paths ───────────────────────────────────────────────────────────────────────
# Student-t runs get their own results/figs subtree so they don't clobber the
# Gaussian checkpoints/figures when switching SPATIAL_DIST back and forth.
_DIST_SUFFIX = "" if SPATIAL_DIST == "gaussian" else f"_{SPATIAL_DIST}"
HOME_DIR  = "/home/a01738353/2024_NEHRP/RECAST/"
DATA_DIR  = f"{HOME_DIR}case_studies/etas2_synthetic/"
SAVE_DIR  = f"{HOME_DIR}results/replicate_ETAS{_DIST_SUFFIX}/"
FIGS_DIR  = f"{HOME_DIR}figs/replicate_ETAS{_DIST_SUFFIX}/"

for d in [SAVE_DIR, FIGS_DIR]:
    os.makedirs(d, exist_ok=True)


#%%
# ─── Section 1: Load metadata ──────────────────────────────────────────────────
# The JSON written by generate_etas_synthetic.py holds all constants we need:
# true ETAS parameters, polygon centroid, km/degree conversion factors, etc.
# Reading them here ensures test_replicate_ETAS.py and generate_etas_synthetic.py
# always agree on the coordinate system without any hardcoding.

with open(f"{DATA_DIR}true_params.json") as f:
    meta = json.load(f)

TRUE_PARAMS  = meta["true_params"]    # dict of raw etas_2 parameter values
LAT_CTR      = meta["lat_ctr"]        # polygon centroid latitude  [°N]
LON_CTR      = meta["lon_ctr"]        # polygon centroid longitude [°W, negative]
KM_PER_LAT   = meta["km_per_lat"]     # ≈ 111.1 km per degree latitude
KM_PER_LON   = meta["km_per_lon"]     # ≈ 91.0 km per degree longitude at 35°N
HALF_KM_LAT  = meta["half_km_lat"]    # ≈ 222 km — N/S half-extent of box
HALF_KM_LON  = meta["half_km_lon"]    # ≈ 182 km — E/W half-extent of box
BOX_AREA_KM2 = meta["box_area_km2"]   # ≈ 161 000 km²
T_DAYS       = meta["t_days"]         # catalog window length = 30 days
MC           = meta["mc"]             # magnitude of completeness = 3.6
MAG_MAX      = meta["mag_max"]        # 8.0 — upper bound for ContinuousMarks
N_CATALOGS   = meta["n_catalogs"]     # 300

# True ETAS parameters in RECAST-comparable units (pre-computed in generation script).
# We print these at the end alongside RECAST's fitted values.
TRUE_P     = meta["recast_p_true"]       # Omori p = 1 + omega
TRUE_C     = meta["recast_c_true"]       # Omori c [days]
TRUE_MU    = meta["recast_mu_rate_true"] # background rate [events/day] over the box
# Spatial parameters — read directly from the true_params dict.
TRUE_D     = 10 ** meta["true_params"]["log10_d"]  # base spatial length scale [km]
TRUE_GAMMA = meta["true_params"]["gamma"]           # magnitude scaling of cluster radius
TRUE_RHO   = meta["true_params"]["rho"]             # spatial power-law decay exponent
# etas_2's `a` is NOT RECAST's alpha. etas_2 writes the offspring rate as
#     k0 · exp(a·Δm) · (r² + d_g)^(−ρ−1),   d_g = d·exp(γ·Δm)   (unnormalized kernel),
# whereas RECAST's ETAS uses  k · 10^(α·Δm) · (ρ/π)·d_g^ρ·(r² + d_g)^(−ρ−1)  (kernel
# normalized to 1). Matching the two (d_g^ρ carries exp(ργΔm)) gives
#     α = (a − ρ·γ) / ln 10      (natural-log → log10, and remove the kernel-norm factor)
#     k = k0 · (π/ρ) · d^(−ρ)
# so the "true" alpha here is ≈ 0.46, not 1.69 (verified: the likelihood at converted
# truth is minimal over an α scan).
TRUE_ALPHA = (meta["true_params"]["a"] - TRUE_RHO * TRUE_GAMMA) / math.log(10)
TRUE_K     = 10 ** meta["true_params"]["log10_k0"] * math.pi / TRUE_RHO * TRUE_D ** (-TRUE_RHO)
# Equivalent-circle radius so that π·R_bg² = box area; makes the background
# density μ/(π·R_bg²) consistent with the uniform-over-box generating process.
TRUE_R_BG  = (BOX_AREA_KM2 / math.pi) ** 0.5       # ≈ 227 km

MIN_EVENTS = 10   # drop catalogs with fewer events than this (too sparse to train on)

print(f"Loaded metadata from {DATA_DIR}true_params.json")
print(f"  True p={TRUE_P:.2f}  c={TRUE_C:.5f} d  alpha={TRUE_ALPHA:.2f}")
print(f"  True mu={TRUE_MU:.3f} events/day (over {BOX_AREA_KM2:.0f} km²)")
print(f"  True d={TRUE_D:.4f} km  gamma={TRUE_GAMMA:.2f}  rho={TRUE_RHO:.2f}  R_bg={TRUE_R_BG:.1f} km")
print(f"  T_DAYS={T_DAYS}  MC={MC}  MAG_MAX={MAG_MAX}")


#%%
# ─── Section 2: Load parquet and convert to RECAST Sequences ──────────────────
#
# etas_2 outputs a DataFrame with columns:
#     catalog_id, latitude [°N], longitude [°W], time [datetime], magnitude
#
# RECAST needs a Sequence object with:
#     inter_times  — time gaps between consecutive events [days]; shape (n+1,)
#                    inter_times[0]  = gap from window start (0.0) to first event
#                    inter_times[-1] = gap from last event to window end (T_DAYS)
#     t_start      — 0.0 (we define each window start as time zero)
#     mag          — ContinuousMarks object wrapping a (n,) float32 tensor
#     x_loc        — km east  of polygon centroid; shape (n,) float32
#     y_loc        — km north of polygon centroid; shape (n,) float32
#
# Coordinate projection:
#     x_km = (longitude − LON_CTR) × KM_PER_LON     east is positive
#     y_km = (latitude  − LAT_CTR) × KM_PER_LAT     north is positive
#
# This is the same flat-Earth (equirectangular) projection used in
# test_case_study.py:load_mainshock_sequence().  It's accurate to ~0.1% over
# the ~400 km extent of our box.

def catalog_to_sequence(df_group):
    """Convert one etas_2 catalog (a sub-DataFrame) to a RECAST Sequence.

    Args:
        df_group: DataFrame rows for a single catalog_id.
                  Expected columns: latitude, longitude, time, magnitude.

    Returns:
        eq.data.Sequence  with inter_times, mag (ContinuousMarks), x_loc, y_loc.
        None if the group has fewer than MIN_EVENTS events.
    """
    # Sort by time (etas_2 may not guarantee order when aftershock generations merge)
    df = df_group.sort_values("time").reset_index(drop=True)
    df = df[df.magnitude >= MC].reset_index(drop=True)

    if len(df) < MIN_EVENTS:
        return None

    # ── Project geographic coordinates to km offsets from the polygon centroid ─
    # "East" and "North" here match the convention in test_case_study.py so that
    # models trained on different datasets share the same spatial semantics.
    x_km = ((df.longitude.values - LON_CTR) * KM_PER_LON).astype(np.float32)
    y_km = ((df.latitude.values  - LAT_CTR) * KM_PER_LAT).astype(np.float32)

    # ── Convert datetime → fractional days since window start ─────────────────
    # Each catalog was generated over a T_DAYS-day window.  We measure time
    # from the window start (t_start = 0.0).  All etas_2 events fall strictly
    # in the open interval (0, T_DAYS), so the first and last inter-times are > 0.
    t_window_start = df["time"].iloc[0].replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    # Round window start to nearest day boundary — etas_2 guarantees events are
    # in (window_start, window_end) so the exact value doesn't affect relative times.
    arrival_days = (df["time"] - t_window_start).dt.total_seconds().values / 86400.0
    # Safety clip: keep all arrivals strictly inside (0, T_DAYS) to avoid
    # zero or negative inter-times at floating-point boundaries.
    arrival_days = np.clip(arrival_days, 1e-6, T_DAYS - 1e-6)

    # inter_times[0]   = arrival_days[0] − 0.0          (gap from window start)
    # inter_times[i]   = arrival_days[i] − arrival_days[i-1]   (event to event)
    # inter_times[-1]  = T_DAYS − arrival_days[-1]       (gap to window end)
    inter_times = np.diff(arrival_days, prepend=[0.0], append=[float(T_DAYS)])

    # ── Wrap magnitudes in ContinuousMarks ─────────────────────────────────────
    # ContinuousMarks stores: the raw magnitude values + (mc, mag_max) bounds
    # used by RecurrentTPP to compute the Gutenberg-Richter log-probability.
    # The ETAS model ignores the bounds and reads only the raw .values tensor.
    mag = eq.data.ContinuousMarks(
        df.magnitude.values.astype(np.float32),
        bounds     = [MC, MAG_MAX],
        nll_bounds = [MC, MAG_MAX],
    )

    return eq.data.Sequence(
        inter_times,
        t_start = 0.0,     # all sequences start at t=0 (window start)
        mag     = mag,
        x_loc   = torch.tensor(x_km),
        y_loc   = torch.tensor(y_km),
    )


raw_df = pd.read_parquet(f"{DATA_DIR}raw_catalogs.parquet")
print(f"Loaded {len(raw_df):,} events from {raw_df.catalog_id.nunique()} catalogs")

# Convert every catalog group to a Sequence (or None if too sparse)
sequences = []
for cat_id, group in raw_df.groupby("catalog_id"):
    seq = catalog_to_sequence(group)
    if seq is not None:
        sequences.append(seq)

print(f"Sequences after ≥{MIN_EVENTS}-event filter: {len(sequences)} / {N_CATALOGS}")

# ── Train / val / test split (60 / 20 / 20) ────────────────────────────────────
# We split by index (not by time) because each catalog is an independent
# realisation — there is no temporal ordering between catalogs to preserve.
n_total = len(sequences)
n_train = int(0.60 * n_total)
n_val   = int(0.20 * n_total)

train_seqs = sequences[:n_train]
val_seqs   = sequences[n_train : n_train + n_val]
test_seqs  = sequences[n_train + n_val :]

train_ds = eq.data.InMemoryDataset(train_seqs)
val_ds   = eq.data.InMemoryDataset(val_seqs)
test_ds  = eq.data.InMemoryDataset(test_seqs)

print(f"Split: {len(train_ds)} train / {len(val_ds)} val / {len(test_ds)} test")

# Quick sanity check on the first training sequence
s0 = train_ds[0]
print(f"\nFirst training sequence:")
print(f"  Events   : {s0.num_events}")
print(f"  Duration : {s0.t_end:.2f} days (should be ≈{T_DAYS})")
print(f"  x range  : [{s0.x_loc.min():.1f}, {s0.x_loc.max():.1f}] km")
print(f"  y range  : [{s0.y_loc.min():.1f}, {s0.y_loc.max():.1f}] km")
print(f"  mag range: [{s0.mag.numpy().min():.1f}, {s0.mag.numpy().max():.1f}]")

#%%
# ── Verify: inspect one loaded sequence — stem plot + spatial scatter ───────────
# Change VERIFY_SEQ_IDX to view a different sequence (0 to len(sequences)-1).

# ── Verify: inspect one loaded sequence — stem plot + spatial scatter ───────────
# Change VERIFY_SEQ_IDX to view a different sequence (0 to len(sequences)-1).

VERIFY_SEQ_IDX = 11

_seq = sequences[VERIFY_SEQ_IDX]
_t   = _seq.arrival_times.numpy()
_m   = _seq.mag.numpy()
_x   = _seq.x_loc.numpy()
_y   = _seq.y_loc.numpy()

fig, (ax_t, ax_s) = plt.subplots(1, 2, figsize=(10, 5))
fig.suptitle(
    f"Loaded Sequence {VERIFY_SEQ_IDX}  ({_seq.num_events} events)",
    fontsize=12,
)

# Top: time-magnitude stem plot
markerline, stemlines, baseline = ax_t.stem(
    _t, _m, markerfmt="C0o", linefmt="C0-", basefmt="k-",
)
markerline.set_visible(False)   # stem markers can't vary in size; use scatter instead
plt.setp(stemlines, linewidth=0.7, alpha=0.6)
ax_t.scatter(_t, _m, s=20 + 15 * (_m - MC)**2, color="C0", zorder=3)
ax_t.axhline(MC, color="gray", linestyle="--", linewidth=0.8, label=f"Mc = {MC}")
ax_t.set_xlim(-1, T_DAYS)
ax_t.set_ylim(1,7)
ax_t.set_xlabel("Time [days since window start]")
ax_t.set_ylabel("Magnitude")
ax_t.legend(fontsize=9)

# Bottom: spatial distribution coloured by magnitude
sc = ax_s.scatter(
    _x, _y,
    c=_m, cmap="hot_r",
    s=20 + 15 * (_m - MC)**2,
    vmin=MC, vmax=max(_m.max(), MC + 1),
    alpha=0.8, edgecolors="k", linewidths=0.3,
)
plt.colorbar(sc, ax=ax_s, label="Magnitude")
ax_s.scatter(_x[0], _y[0], marker="*", s=150, color="red", zorder=5, label="First event")
ax_s.axhline(0, color="k", lw=0.5, ls="--")
ax_s.axvline(0, color="k", lw=0.5, ls="--")
ax_s.set_xlim(-HALF_KM_LON, HALF_KM_LON)
ax_s.set_ylim(-HALF_KM_LAT, HALF_KM_LAT)
ax_s.set_xlabel("East of box center [km]")
ax_s.set_ylabel("North of box center [km]")
ax_s.set_aspect("equal", adjustable="box")
ax_s.legend(fontsize=9)

plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/verify_sequence_{VERIFY_SEQ_IDX:03d}.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 3: Normalization statistics ───────────────────────────────────────
# RecurrentTPP encodes events as:
#   time  → log(τ) − log(τ_mean)          (log inter-time, zero-centred)
#   space → (x − x_mean) / x_std,  same for y
#   mag   → (m − Mc)                       (no normalisation needed; already ≥ 0)
#
# We compute τ_mean, x_mean, x_std, y_mean, y_std from the TRAINING set only
# and register them as fixed buffers in the model.  Applying them to val/test
# sequences is valid because ETAS is stationary: the population statistics are
# the same everywhere in the box and across all time windows.

all_x   = np.concatenate([s.x_loc.numpy() for s in train_ds])
all_y   = np.concatenate([s.y_loc.numpy() for s in train_ds])
all_tau = np.concatenate([s.inter_times[:-1].numpy() for s in train_ds])

# x_mean ≈ 0, y_mean ≈ 0 because etas_2 uses a uniform background and the
# box is centred on (LAT_CTR, LON_CTR).  We set them explicitly to 0 rather
# than estimating them to avoid fitting noise.
x_mean, y_mean = 0.0, 0.0
x_std    = float(all_x.std())
y_std    = float(all_y.std())
tau_mean = float(all_tau.mean())

print(f"Normalization (from {len(train_ds)} training sequences):")
print(f"  tau_mean = {tau_mean:.4f} days")
print(f"  x_std    = {x_std:.1f} km")
print(f"  y_std    = {y_std:.1f} km")


#%%
# ─── Section 5: Fit RECAST's ETAS model — spatio-temporal NLL baseline ────────
#
# Before training RecurrentTPP we fit RECAST's built-in parametric ETAS model
# to the same training sequences.  This gives us:
#   (a) A BASELINE NLL that RecurrentTPP should eventually beat (or match).
#   (b) A PARAMETER RECOVERY check: do the fitted p, c, alpha, mu, d, gamma, rho
#       match the true values used in data generation?
#
# NLL COMPARABILITY:
#   Both models are scored as the likelihood of the observed events in the box W
#   over [0, T], per day and per km²:
#       ETAS:   −[Σ log λ(tᵢ,rᵢ) − ∫_W∫λ] / T
#       RECAST: −[Σ log f(τᵢ) + Σ log p_W(rᵢ|τᵢ,cᵢ) + log S(T − t_n)] / T
#   (time_weight = spatial_weight = 1; neither includes a magnitude term.)  This is
#   an exact equality of likelihoods when
#     - both spatial densities are per km² (RECAST's nll_loss applies the 1/(σx σy)
#       Jacobian),
#     - both are normalized over W: ETAS multiplies each parent's offspring integral
#       by the fraction of its kernel inside W and uses a uniform-on-rectangle
#       background (spatial_window); RECAST's mixture is renormalized by P(r ∈ W)
#       (window= argument of nll_loss, Monte Carlo).
#   The etas_2 generator discards events outside the polygon, so this is the process
#   that actually produced the data.

WINDOW = (-HALF_KM_LON, HALF_KM_LON, -HALF_KM_LAT, HALF_KM_LAT)   # km, box centred at 0

etas_baseline = ETAS(
    mag_completeness         = MC,
    richter_b                = 1.0,
    use_spatial              = True,
    # Initialise near the true values so the optimizer doesn't wander far.
    omori_p_init             = TRUE_P,
    omori_c_init             = TRUE_C,
    productivity_k_init      = TRUE_K,
    productivity_alpha_init  = TRUE_ALPHA,
    base_rate_init           = max(TRUE_MU, 0.01),
    spatial_d_init           = TRUE_D,
    spatial_gamma_init       = TRUE_GAMMA,
    spatial_rho_init         = TRUE_RHO,
    spatial_window           = WINDOW,
    report_params            = False,
    learning_rate            = 5e-3,
)

#%%
_RETRAIN_ETAS_ = not os.path.exists(f"{SAVE_DIR}/etas_baseline_spatial_window.pt")

if _RETRAIN_ETAS_:
    # ── Manual training loop (no Lightning) ────────────────────────────────────
    # Full-batch gradient descent: all training sequences in one batch.
    # This is fine because N_train ≈ 180 sequences × 30 days is small.
    train_batch_etas = eq.data.Batch.from_list(train_seqs)
    etas_optimizer   = torch.optim.Adam(etas_baseline.parameters(), lr=5e-3)

    ETAS_EPOCHS = 200
    etas_losses = []

    print(f"Training ETAS baseline for {ETAS_EPOCHS} epochs...")
    print(f"                        p={TRUE_P:>10.3f}  c={TRUE_C:>10.5f}  mu={TRUE_MU:>10.4f} \
       alpha={TRUE_ALPHA:>10.3f}  d={TRUE_D:>10.4f} \
       gamma={TRUE_GAMMA:>10.4f}  rho={TRUE_RHO:>10.4f}")
    etas_baseline.train()
    for epoch in range(ETAS_EPOCHS):
        etas_optimizer.zero_grad()
        # nll_loss returns one scalar per sequence; we average across the batch.
        nll = etas_baseline.nll_loss(train_batch_etas).mean()
        nll.backward()
        # Gradient clipping prevents log-space parameters from exploding early on.
        torch.nn.utils.clip_grad_norm_(etas_baseline.parameters(), 1.0)
        etas_optimizer.step()
        etas_losses.append(nll.item())

        if (epoch + 1) % 100 == 0:
            print(f"  Epoch {epoch+1:4d}  NLL={nll.item():.4f}  "
                  f"p={etas_baseline.p.item():.3f}  "
                  f"c={etas_baseline.c.item():.5f}  "
                  f"mu={etas_baseline.mu.item():.4f}  "
                  f"alpha={etas_baseline.alpha.item():.3f}  "
                  f"d={etas_baseline.d.item():.4f}  "
                  f"gamma={etas_baseline.gamma.item():.3f}  "
                  f"rho={etas_baseline.rho.item():.3f}")

    torch.save(etas_baseline.state_dict(), f"{SAVE_DIR}/etas_baseline_spatial_window.pt")

    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(etas_losses, linewidth=0.8, color='darkorange')
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Mean NLL / day")
    ax.set_title("ETAS baseline training loss (spatial)")
    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/etas_training_loss.png", dpi=150, bbox_inches='tight')
    plt.show()

#%%
etas_baseline.load_state_dict(torch.load(f"{SAVE_DIR}/etas_baseline_spatial_window.pt",
                                          map_location='cpu'))
etas_baseline.eval()
print(f"Loaded ETAS checkpoint from {SAVE_DIR}/etas_baseline_spatial_window.pt")

# ── Parameter recovery table ────────────────────────────────────────────────────
print("\nParameter recovery (True vs. ETAS-fitted):")
print(f"  {'Parameter':14s}  {'True':>10s}  {'Fitted':>10s}  Note")
print(f"  {'-'*14}  {'-'*10}  {'-'*10}  {'-'*35}")
print(f"  {'p':14s}  {TRUE_P:>10.3f}  "
      f"{etas_baseline.p.item():>10.3f}  Omori decay exponent")
print(f"  {'c (days)':14s}  {TRUE_C:>10.5f}  "
      f"{etas_baseline.c.item():>10.5f}  Omori time offset")
print(f"  {'alpha':14s}  {TRUE_ALPHA:>10.3f}  "
      f"{etas_baseline.alpha.item():>10.3f}  Productivity magnitude scaling")
print(f"  {'mu (ev/day)':14s}  {TRUE_MU:>10.4f}  "
      f"{etas_baseline.mu.item():>10.4f}  Background rate (total, box area)")
print(f"  {'d (km)':14s}  {TRUE_D:>10.4f}  "
      f"{etas_baseline.d.item():>10.4f}  Base spatial length scale")
print(f"  {'gamma':14s}  {TRUE_GAMMA:>10.3f}  "
      f"{etas_baseline.gamma.item():>10.3f}  Magnitude scaling of cluster radius")
print(f"  {'rho':14s}  {TRUE_RHO:>10.3f}  "
      f"{etas_baseline.rho.item():>10.3f}  Spatial power-law decay exponent")


# ── ETAS test NLL (the baseline to beat) ────────────────────────────────────────
test_batch = eq.data.Batch.from_list(test_seqs)
with torch.no_grad():
    etas_test_nll = etas_baseline.nll_loss(test_batch).mean().item()
print(f"\nETAS spatio-temporal NLL on test set (window-normalized): {etas_test_nll:.4f} per day")


#%%
# ─── Section 6: Define and train RecurrentTPP ─────────────────────────────────
#
# Architecture (from eq/models/recurrent.py):
#   Encoder: each event → [log(τ) − log(τ_mean), (x−x_mean)/x_std,
#                           (y−y_mean)/y_std, (m−Mc)]  — a 4-dimensional vector
#   RNN (GRU): encodes event history → context vector of size context_size
#   Decoders (hypernets):
#     hypernet_time → Weibull mixture parameters (num_components_time components)
#     hypernet_xy   → 2D Gaussian mixture parameters with Cholesky covariance
#     hypernet_mag  → Gutenberg-Richter parameters (effectively learns b-value)
#
# NLL loss returned per sequence per day:
#   − [log p(inter_times) + spatial_weight × log p(x_loc, y_loc) + log S(t_last)
#      − log S(t_first)]  /  (t_end − t_nll_start)
#
# time_weight = spatial_weight = 1 (constructor defaults), so the loss is a true
# likelihood; the spatial density is per km² (Jacobian applied in nll_loss).
#
# MODEL SIZE: We use a smaller model than test_case_study.py (context_size=64
# vs 256) because the synthetic sequences are shorter (30 vs 365 days) and
# the ETAS dynamics are simpler than real multi-sequence global seismicity.

model = eq.models.RecurrentTPP(
    context_size         = 64,    # RNN hidden-state dimension
    num_components_time  = 8,     # Weibull mixture components for time
    num_components_space = 16,    # mixture components for space
    tau_mean             = tau_mean,
    x_mean               = x_mean,
    y_mean               = y_mean,
    x_std                = x_std,
    y_std                = y_std,
    spatial_weight       = 1,
    spatial_dist          = SPATIAL_DIST,
    spatial_df            = SPATIAL_DF,
)
print(f"RecurrentTPP parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Spatial component distribution: {SPATIAL_DIST}"
      + (f" (df={SPATIAL_DF})" if SPATIAL_DIST == "student_t" else ""))
#%%
# ── Training configuration ──────────────────────────────────────────────────────
_RETRAIN_   = False   # set False to skip training and just load the saved checkpoint
EPOCHS      = 900
BATCH_SIZE  = 32


if _RETRAIN_:
    device    = 'cuda' if torch.cuda.is_available() else 'cpu'
    model     = model.to(device)
    print(f"Training RecurrentTPP on: {device}")

    optimizer    = torch.optim.Adam(model.parameters(), lr=5e-4)
    scheduler    = CosineAnnealingLR(optimizer, T_max=EPOCHS)
    train_loader = DataLoader(
        train_ds,
        batch_size  = BATCH_SIZE,
        shuffle     = True,
        collate_fn  = eq.data.Batch.from_list,   # no jitter (see note above)
    )
    val_batch = eq.data.Batch.from_list(val_seqs).to(device)

    train_losses, val_losses = [], []
    model.train()
    for epoch in range(EPOCHS):
        epoch_losses = []
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            nll = model.nll_loss(batch).mean()
            nll.backward()
            # Clip gradients to prevent parameter explosions (especially early on
            # when the context vectors are near-random and spatial NLL can spike).
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_losses.append(nll.item())

        # Validation NLL — computed without gradients on the full validation set.
        with torch.no_grad():
            v_nll = model.nll_loss(val_batch).mean().item()

        epoch_mean = float(np.mean(epoch_losses))
        train_losses.append(epoch_mean)
        val_losses.append(v_nll)
        scheduler.step()

        if (epoch + 1) % 25 == 0:
            print(f"Epoch {epoch+1:3d}  train={epoch_mean:.4f}  val={v_nll:.4f}")

    torch.save(model.state_dict(), f"{SAVE_DIR}/recast_etas2.pt")

    fig, ax = plt.subplots(figsize=(9, 3))
    ax.plot(train_losses, label='train', color='steelblue', lw=0.9)
    ax.plot(val_losses,   label='val',   color='orange',    lw=0.9)
    ax.axhline(etas_test_nll, ls='--', color='red', lw=1.2, label='ETAS temporal NLL')
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Mean NLL / day")
    ax.set_title("RecurrentTPP training loss  (dashed = ETAS temporal baseline)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/recast_training_loss.png", dpi=150, bbox_inches='tight')
    plt.show()


#%%
# ─── Section 7: Load trained model ────────────────────────────────────────────
map_location = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.cpu()
model.load_state_dict(torch.load(f"{SAVE_DIR}/recast_etas2.pt",
                                  map_location='cpu'))
model.eval()
print(f"Loaded checkpoint from {SAVE_DIR}/recast_etas2.pt")


#%%
# ─── Section 8: NLL comparison table ──────────────────────────────────────────
# Evaluate both models on the held-out test set and print a comparison.
# Both NLLs are the likelihood of the observed events in the box W (per day, per km²);
# see the Section 5 comment for why they are directly comparable.

with torch.no_grad():
    model = model.cpu()
    test_batch = test_batch.to('cpu')
    recast_test_nll       = model.nll_loss(test_batch, window=WINDOW).mean().item()
    recast_test_nll_plane = model.nll_loss(test_batch).mean().item()  # mixture not renormalized to W

print("\n" + "="*62)
print(f"  {'Model':40s}  {'NLL / day':>10s}")
print(f"  {'-'*40}  {'-'*10}")
print(f"  {'ETAS (spatio-temporal, window)':40s}  {etas_test_nll:>10.4f}")
print(f"  {'RecurrentTPP (window-normalized)':40s}  {recast_test_nll:>10.4f}")
print(f"  {'RecurrentTPP (unnormalized, for ref.)':40s}  {recast_test_nll_plane:>10.4f}")
print("="*62)
print("  Lower = better at predicting held-out sequences.")


#%%
# ─── Section 9: Cumulative count forecast — etas_2 (true model) vs. RECAST ───
# Both forecasts are conditioned on the SAME first `condition_days` of seq_ref.
#
# Left panel:  etas_2's simulate_catalog_continuation() using TRUE_PARAMS —
#              the actual generative model, not a re-fit approximation.
# Right panel: RECAST RecurrentTPP sampled forward from the same history.
#
# Conversion: cond_seq (km offsets, fractional days) → lat/lon DataFrame for
# etas_2 → simulated events → fractional days for the count grid.

import datetime as dt
import logging
from shapely.geometry import Polygon as ShapelyPolygon
from etas.simulation import simulate_catalog_continuation

logging.getLogger("etas").setLevel(logging.WARNING)  # suppress etas_2 verbosity

condition_days = 5
FORECAST_BATCH = 200

# ── Reconstruct the study-area polygon from metadata ─────────────────────────
# etas_2 uses (lat, lon) as (x, y) internally (consistent with its gpd calls).
LAT_MIN = LAT_CTR - HALF_KM_LAT / KM_PER_LAT
LAT_MAX = LAT_CTR + HALF_KM_LAT / KM_PER_LAT
LON_MIN = LON_CTR - HALF_KM_LON / KM_PER_LON
LON_MAX = LON_CTR + HALF_KM_LON / KM_PER_LON
polygon = ShapelyPolygon([
    [LAT_MIN, LON_MIN], [LAT_MAX, LON_MIN],
    [LAT_MAX, LON_MAX], [LAT_MIN, LON_MAX],
])
beta_main = np.log(10) * meta["richter_b"]

# Arbitrary epoch — only relative times matter for the simulation.
T_REF = dt.datetime(2020, 1, 1, 0, 0, 0)

# ── Reference sequence and split ──────────────────────────────────────────────
seq_ref       = test_ds[1]
forecast_days = float(seq_ref.t_end) - condition_days
cond_seq      = seq_ref.get_subsequence(seq_ref.t_start, condition_days)
print(f"Reference sequence: {seq_ref.num_events} total events")
print(f"  Conditioning on  t ∈ [0, {condition_days:.0f}) days ({cond_seq.num_events} events)")
print(f"  Forecasting      t ∈ [{condition_days:.0f}, {seq_ref.t_end:.0f}] days")

T_SHOW = float(forecast_days)
N_GRID = 300
t_grid = np.linspace(0, T_SHOW, N_GRID)


def cond_seq_to_df(seq):
    """Convert a RECAST Sequence to an etas_2 auxiliary_catalog DataFrame.

    Converts fractional-day arrival times to datetimes relative to T_REF, and
    km offsets back to lat/lon using the box centroid and scale factors.
    """
    times = seq.arrival_times.numpy()
    lats  = seq.y_loc.numpy() / KM_PER_LAT + LAT_CTR
    lons  = seq.x_loc.numpy() / KM_PER_LON + LON_CTR
    mags  = seq.mag.numpy()
    return pd.DataFrame({
        'latitude':  lats,
        'longitude': lons,
        'time':      [T_REF + dt.timedelta(days=float(t)) for t in times],
        'magnitude': mags,
        'xi_plus_1': 1.0,
    })


def forecast_cumulative(batch, t_cut, t_grid):
    """Cumulative event count relative to t_cut for each sampled RECAST trajectory.

    Args:
        batch  : Batch returned by model.sample().
        t_cut  : Conditioning cutoff time (fractional days).
        t_grid : 1-D array of relative times at which to evaluate the count.

    Returns:
        cum: int array of shape (batch_size, len(t_grid)).
    """
    cum = np.zeros((batch.batch_size, len(t_grid)), dtype=int)
    for i in range(batch.batch_size):
        n        = int(batch.end_idx[i])
        times    = batch.arrival_times[i, :n].numpy()
        fore_rel = np.sort(times[times > t_cut] - t_cut)
        cum[i]   = np.searchsorted(fore_rel, t_grid, side='right')
    return cum


# Observed step function for the reference sequence
obs_times_rel = seq_ref.arrival_times.numpy() - condition_days
obs_fore      = np.sort(obs_times_rel[obs_times_rel > 0])
obs_cum       = np.searchsorted(obs_fore, t_grid, side='right')

# ── etas_2 conditional forecast (true generative model, TRUE_PARAMS) ──────────
print(f"Sampling {FORECAST_BATCH} etas_2 trajectories (true generative model)...")
cond_df  = cond_seq_to_df(cond_seq)
aux_end  = T_REF + dt.timedelta(days=condition_days)
sim_end  = T_REF + dt.timedelta(days=float(seq_ref.t_end))

etas2_cum = np.zeros((FORECAST_BATCH, len(t_grid)), dtype=int)
for sim_id in range(FORECAST_BATCH):
    sim = simulate_catalog_continuation(
        auxiliary_catalog = cond_df,
        auxiliary_start   = T_REF,
        auxiliary_end     = aux_end,
        polygon           = polygon,
        simulation_end    = sim_end,
        parameters        = TRUE_PARAMS,
        mc                = MC,
        beta_main         = beta_main,
        m_max             = MAG_MAX,
        filter_polygon    = False,   # skip geopandas filtering — saves ~30 % time
        approx_times      = True,    # faster Omori inversion approximation
    )
    sim_fore   = sim[sim['time'] > aux_end]
    times_days = np.array(
        [(t - T_REF).total_seconds() / 86400.0 for t in sim_fore['time']]
    )
    fore_rel = np.sort(times_days - condition_days)
    fore_rel = fore_rel[fore_rel > 0]
    etas2_cum[sim_id] = np.searchsorted(fore_rel, t_grid, side='right')
    if (sim_id + 1) % 50 == 0:
        print(f"  {sim_id + 1}/{FORECAST_BATCH}")

e_q10, e_q25, e_q75, e_q90 = np.percentile(etas2_cum, [10, 25, 75, 90], axis=0)

# ── RECAST conditional forecast ───────────────────────────────────────────────
print(f"Sampling {FORECAST_BATCH} RECAST trajectories...")
model.eval()
with torch.no_grad():
    recast_pred = model.sample(
        batch_size       = FORECAST_BATCH,
        duration         = forecast_days,
        t_start          = condition_days,
        past_seq         = cond_seq,
        mag_completeness = MC,
    )
recast_cum = forecast_cumulative(recast_pred, condition_days, t_grid)
r_q10, r_q25, r_q75, r_q90 = np.percentile(recast_cum, [10, 25, 75, 90], axis=0)

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4), sharey=True)
fig.suptitle(
    f"Cumulative count forecast — both conditioned on first {condition_days} days of ref seq",
    fontsize=11,
)

for ax, cum_q10, cum_q25, cum_q75, cum_q90, color, label in [
    (axes[0], e_q10, e_q25, e_q75, e_q90, 'darkorange',
     f'etas_2 (true model, {FORECAST_BATCH} samples)'),
    (axes[1], r_q10, r_q25, r_q75, r_q90, 'steelblue',
     f'RECAST RecurrentTPP ({FORECAST_BATCH} samples)'),
]:
    ax.fill_between(t_grid, cum_q10, cum_q90, alpha=0.20, color=color, label='q10–q90')
    ax.fill_between(t_grid, cum_q25, cum_q75, alpha=0.45, color=color, label='q25–q75')
    ax.step(np.concatenate([[0], t_grid]),
            np.concatenate([[0], obs_cum]),
            where='post', color='k', linewidth=1.8, label='Ref seq (observed)', zorder=5)
    ax.set_xlabel("Days after conditioning cutoff")
    ax.set_ylabel("Cumulative events")
    ax.set_title(label, fontsize=9)
    ax.legend(fontsize=8)
    ax.set_xlim(0, T_SHOW)
    ax.set_ylim(bottom=0)

plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/forecast_cumulative.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 9b: Reference vs. 50 RECAST forecasts, as heatmaps ───────────────
from matplotlib.colors import LogNorm

N_FORECASTS = 250
DAY_BIN, MAG_BIN, KM_BIN = 1.0, 0.25, 20.0   # one time/mag cell is drawn square

with torch.no_grad():
    ens = model.sample(
        batch_size       = N_FORECASTS,
        duration         = forecast_days,
        t_start          = condition_days,
        past_seq         = cond_seq,
        mag_completeness = MC,
    )

e_t, e_m, e_x, e_y = [], [], [], []
for i in range(ens.batch_size):
    keep = ~ens.mask[i].bool()
    e_t.append(ens.arrival_times[i][keep].numpy())
    e_m.append(ens.mag[i][keep].numpy())
    e_x.append(ens.x_loc[i][keep].numpy())
    e_y.append(ens.y_loc[i][keep].numpy())
e_t, e_m, e_x, e_y = map(np.concatenate, (e_t, e_m, e_x, e_y))

ref_t, ref_m = seq_ref.arrival_times.numpy(), seq_ref.mag.numpy()
ref_x, ref_y = seq_ref.x_loc.numpy(), seq_ref.y_loc.numpy()
ref_cond = ref_t <= condition_days


def _msize(m):
    return 12 * (np.asarray(m) - MC + 1) ** 2


fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Panel 1: magnitude vs. day, mean events per cell per forecast
t_edges = np.arange(condition_days, float(seq_ref.t_end) + DAY_BIN, DAY_BIN)
m_edges = np.arange(MC, MAG_MAX + MAG_BIN, MAG_BIN)
H, _, _ = np.histogram2d(e_t, e_m, bins=[t_edges, m_edges])
H /= N_FORECASTS
pm = axes[0].pcolormesh(t_edges, m_edges, np.ma.masked_equal(H, 0).T, cmap='Blues',
                        norm=LogNorm(vmin=1 / N_FORECASTS, vmax=max(H.max(), 1)))
fig.colorbar(pm, ax=axes[0], label='Mean events per cell per forecast')
axes[0].scatter(ref_t, ref_m, s=_msize(ref_m), color='red', zorder=3, label='Reference seq')
axes[0].axvline(condition_days, color='k', ls='--', label='Condition cutoff')
axes[0].set_xlim(0, float(seq_ref.t_end))
axes[0].set_ylim(MC, MAG_MAX)
axes[0].set_aspect(DAY_BIN / MAG_BIN, adjustable='box')   # cells square on screen
axes[0].set_xlabel("Days")
axes[0].set_ylabel("Magnitude")
axes[0].set_title(f"Forecast density ({N_FORECASTS} samples)")
axes[0].legend()

# Panel 2: map view, mean events per cell per forecast
x_edges = np.arange(-HALF_KM_LON, HALF_KM_LON + KM_BIN, KM_BIN)
y_edges = np.arange(-HALF_KM_LAT, HALF_KM_LAT + KM_BIN, KM_BIN)
Hxy, _, _ = np.histogram2d(e_x, e_y, bins=[x_edges, y_edges])
Hxy /= N_FORECASTS
pm = axes[1].pcolormesh(x_edges, y_edges, np.ma.masked_equal(Hxy, 0).T, cmap='Blues',
                        norm=LogNorm(vmin=1 / N_FORECASTS, vmax=max(Hxy.max(), 1)))
fig.colorbar(pm, ax=axes[1], label='Mean events per cell per forecast')
axes[1].scatter(ref_x[ref_cond], ref_y[ref_cond], s=_msize(ref_m[ref_cond]),
                color='salmon', alpha=0.6, label='Reference (condition)')
axes[1].scatter(ref_x[~ref_cond], ref_y[~ref_cond], s=_msize(ref_m[~ref_cond]),
                color='red', alpha=0.8, label='Reference (forecast period)')
axes[1].set_xlim(-HALF_KM_LON, HALF_KM_LON)
axes[1].set_ylim(-HALF_KM_LAT, HALF_KM_LAT)
axes[1].set_aspect('equal')
axes[1].set_xlabel("East of box center (km)")
axes[1].set_ylabel("North of box center (km)")
axes[1].set_title(f"Forecast density, {KM_BIN:g} km cells")
axes[1].legend()
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/forecast_heatmaps.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 10: Inter-event time distributions ───────────────────────────────
# Compare the inter-event time density learned by RECAST against the empirical
# histogram from all training sequences.
#
# RECAST's time decoder is a Weibull mixture (plot_time_mixture from
# plot_helpers.py).  We show two contexts:
#   Left:  zero context — the model's "prior" before seeing any events.
#          Should match the average inter-event distribution from training.
#   Right: context after conditioning on the reference sequence (first half).
#          Should show shorter inter-times if a burst just occurred (Omori effect).

# Aggregate inter-event times from 50 training sequences for the histogram
training_inter = np.concatenate([
    train_ds[i].inter_times[:-1].numpy()
    for i in range(min(50, len(train_ds)))
])

# Inter-event times after the conditioning cutoff from the reference sequence
post_cond_inter = cond_seq.inter_times[:-1].numpy()
# Also grab post-condition events from seq_ref for a richer histogram
post_ref = seq_ref.get_subsequence(condition_days, seq_ref.t_end)
post_ref_inter = post_ref.inter_times[:-1].numpy() if post_ref.num_events > 0 else np.array([])

# Context vectors
context_zero = torch.zeros(1, 1, model.context_size)
cond_batch   = eq.data.Batch.from_list([cond_seq])
with torch.no_grad():
    context_cond = model.get_context(cond_batch)[:, [-1], :]   # last context vector

T_MAX = 5.0   # x-axis limit for the density plot [days]
Y_MAX = 40    # y-axis limit for density

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

for ax, ctx, title, obs_inter, obs_label in [
    (axes[0], context_zero, 'Prior (zero context)',
     training_inter, f"Training sequences (50 of {len(train_ds)})"),
    (axes[1], context_cond,
     f'After conditioning ({cond_seq.num_events} events, t=0–{condition_days:.0f} d)',
     post_ref_inter, "Reference seq (post-condition)"),
]:
    plot_time_mixture(model, ctx, ax, t_max=T_MAX)
    if len(obs_inter) > 0:
        # Log-spaced bins to show the long tail
        bins = np.logspace(-3, np.log10(T_MAX * 3), 60)
        ax.hist(obs_inter, bins=bins, density=True,
                alpha=0.35, color='red', rwidth=0.9, label=obs_label)
    ax.set_xlabel("Inter-event time (days)")
    ax.set_ylabel("Density")
    ax.set_xlim([0, T_MAX * 0.2])
    ax.set_ylim([0, Y_MAX*0.2])
    ax.set_title(title)
    ax.legend(fontsize=8)

plt.suptitle("Weibull inter-event time mixture — RECAST", fontsize=12)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/time_mixture.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 11: Spatial Gaussian mixture — prior vs. conditioned ─────────────
# Visualise the spatial distribution learned by RECAST's hypernet_xy.
#   Left:  zero-context prior — should be a diffuse distribution covering
#          roughly the extent of the training box.
#   Right: conditioned on the first half of the reference sequence — may show
#          tighter clusters around recently active regions if the model has
#          learned the aftershock kernel.

TAU_VIZ = 0.5   # [days] — inter-time shown to the spatial decoder.
                 # Small τ emphasises the near-source zone; large τ gives background.

fig, axes = plt.subplots(1, 2, figsize=(13, 6))

for ax, ctx, title in [
    (axes[0], context_zero, 'Spatial prior  (zero context)'),
    (axes[1], context_cond, f'After conditioning  ({cond_seq.num_events} events)'),
]:
    # A few training sequences in grey for scale
    for i in range(min(8, len(train_ds))):
        s = train_ds[i]
        ax.scatter(s.x_loc.numpy(), s.y_loc.numpy(), s=2, alpha=0.12, c='grey', zorder=1)

    plot_xy_mixture(model, ctx, ax, alpha=0.06, tau=TAU_VIZ)

    # Box boundary dashes
    ax.axhline(0, color='k', lw=0.5, ls='--')
    ax.axvline(0, color='k', lw=0.5, ls='--')
    ax.set_xlim(-HALF_KM_LON * 1.05, HALF_KM_LON * 1.05)
    ax.set_ylim(-HALF_KM_LAT * 1.05, HALF_KM_LAT * 1.05)
    ax.set_xlabel("East of box center (km)")
    ax.set_ylabel("North of box center (km)")
    ax.set_title(title)

# Overlay reference events on the conditioned panel
axes[1].scatter(
    seq_ref.x_loc.numpy(), seq_ref.y_loc.numpy(),
    s=(seq_ref.mag.numpy() - MC + 0.5) ** 2 * 8,
    c='dodgerblue', alpha=0.7, edgecolors='k', linewidths=0.3,
    zorder=5, label=f'Reference seq (M≥{MC})'
)
axes[1].legend(fontsize=8)

plt.suptitle(f"Spatial Gaussian mixture  |  τ = {TAU_VIZ} days", fontsize=12)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/spatial_mixture.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 12: Spatial forecast — expected event count grid ─────────────────
# Sample RECAST trajectories and bin forecast events into a 2-D grid.
# The expected count per cell (total events / trajectories) visualises where
# the model predicts seismicity to concentrate over the forecast window.

NX, NY = 50, 50

x_bins = np.linspace(-HALF_KM_LON, HALF_KM_LON, NX + 1)
y_bins = np.linspace(-HALF_KM_LAT, HALF_KM_LAT, NY + 1)

all_x, all_y, all_m = [], [], []
for i in range(recast_pred.batch_size):
    mask = recast_pred.mask[i].bool()
    all_x.append(recast_pred.x_loc[i][~mask].numpy())
    all_y.append(recast_pred.y_loc[i][~mask].numpy())
    all_m.append(recast_pred.mag[i][~mask].numpy())

all_x = np.concatenate(all_x)
all_y = np.concatenate(all_y)
all_m = np.concatenate(all_m)

# Only count events inside the grid domain (avoids edge inflation from digitize)
in_domain = (
    (all_x >= x_bins[0]) & (all_x < x_bins[-1]) &
    (all_y >= y_bins[0]) & (all_y < y_bins[-1])
)
all_x, all_y, all_m = all_x[in_domain], all_y[in_domain], all_m[in_domain]

ix = np.digitize(all_x, x_bins) - 1
iy = np.digitize(all_y, y_bins) - 1

count_grid = np.zeros((NX, NY))
for ci in range(NX):
    for cj in range(NY):
        sel = (ix == ci) & (iy == cj)
        count_grid[ci, cj] = sel.sum() / recast_pred.batch_size

count_grid = np.where(count_grid > 0, count_grid, np.nan)
extent = [x_bins[0], x_bins[-1], y_bins[0], y_bins[-1]]

fig, ax = plt.subplots(figsize=(7, 7))
cmap = plt.cm.Blues.copy()
cmap.set_bad('lightgrey')
im = ax.imshow(
    count_grid.T, origin='lower', extent=extent, aspect='auto', cmap=cmap
)
plt.colorbar(im, ax=ax, label="Expected events / cell")
# Observed reference events (condition = orange, forecast window = blue)
cond_mask = seq_ref.arrival_times.numpy() <= condition_days
ax.scatter(seq_ref.x_loc.numpy()[cond_mask],  seq_ref.y_loc.numpy()[cond_mask],
           s=8, color='orange', alpha=0.8, label='Observed (conditioning)')
ax.scatter(seq_ref.x_loc.numpy()[~cond_mask], seq_ref.y_loc.numpy()[~cond_mask],
           s=8, color='red',    alpha=0.8, label='Observed (forecast window)')
ax.axhline(0, color='w', lw=0.5, ls='--')
ax.axvline(0, color='w', lw=0.5, ls='--')
ax.set_xlabel("East of box center (km)")
ax.set_ylabel("North of box center (km)")
ax.set_title(f"RECAST expected event count\n(conditioning: first {condition_days:.0f} d, "
             f"forecast: last {forecast_days:.0f} d)")
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/spatial_forecast_grid.png", dpi=150, bbox_inches='tight')
plt.show()


#%%
# ─── Section 13: Data quantity sweep ──────────────────────────────────────────
# Key research question: how much data does RecurrentTPP need to match ETAS?
#
# For each N in N_TRAIN_SIZES we:
#   1. Take the first N sequences from the training set.
#   2. Train a fresh RecurrentTPP for SWEEP_EPOCHS epochs.
#   3. Evaluate its NLL on the full test set.
#
# The ETAS baseline NLL (from Section 5) is shown as a dashed horizontal line.
# When the RECAST curve crosses below this line, RECAST has exceeded the
# parametric model's predictive accuracy.
#
# NOTE: SWEEP_EPOCHS is intentionally short (50 epochs) so each point can be
# trained in seconds.  The NLLs therefore reflect early-convergence performance,
# not the fully-trained model.  Increase SWEEP_EPOCHS for a more accurate sweep
# at the cost of longer runtime.

N_TRAIN_SIZES = [5, 10, 25, 50, 100, len(train_seqs)]
SWEEP_EPOCHS  = 50

sweep_nlls = []
print(f"\nData quantity sweep  ({len(N_TRAIN_SIZES)} points × {SWEEP_EPOCHS} epochs each)")

for n_train in N_TRAIN_SIZES:
    # Fresh model with the same architecture every time (no warm-start)
    m_sweep = eq.models.RecurrentTPP(
        context_size         = 64,
        num_components_time  = 8,
        num_components_space = 16,
        tau_mean             = tau_mean,
        x_mean               = x_mean,
        y_mean               = y_mean,
        x_std                = x_std,
        y_std                = y_std,
        spatial_dist          = SPATIAL_DIST,
        spatial_df            = SPATIAL_DF,
    )
    opt_sweep = torch.optim.Adam(m_sweep.parameters(), lr=5e-4)

    # Build a DataLoader from the first n_train sequences
    subset_ds     = eq.data.InMemoryDataset(train_seqs[:n_train])
    loader_sweep  = DataLoader(
        subset_ds,
        batch_size = min(32, n_train),    # smaller batch when n_train is tiny
        shuffle    = True,
        collate_fn = eq.data.Batch.from_list,
    )

    m_sweep.train()
    for _ in range(SWEEP_EPOCHS):
        for batch in loader_sweep:
            opt_sweep.zero_grad()
            model.nll_loss(batch).mean().backward() if False else \
            m_sweep.nll_loss(batch).mean().backward()
            torch.nn.utils.clip_grad_norm_(m_sweep.parameters(), 1.0)
            opt_sweep.step()

    m_sweep.eval()
    with torch.no_grad():
        nll_sweep = m_sweep.nll_loss(test_batch, window=WINDOW).mean().item()
    sweep_nlls.append(nll_sweep)
    print(f"  N_train={n_train:4d}  test NLL={nll_sweep:.4f}")

#%%
# ── Plot ────────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 4))
ax.semilogx(N_TRAIN_SIZES, sweep_nlls, 'o-', color='darkblue',
            linewidth=1.5, markersize=6, label='RECAST')
ax.axhline(etas_test_nll, ls='--', color='darkred', lw=1.5,
           label=f'ETAS baseline  ({etas_test_nll:.4f})')
ax.set_xlabel("Number of training sequence")
ax.set_ylabel("Test NLL / day")
#ax.set_title(f"Data quantity sweep  ({SWEEP_EPOCHS} epochs each)\n"
             #"How much data does RECAST need to match ETAS?")
ax.legend()
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/data_quantity_sweep.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"\nETAS baseline NLL : {etas_test_nll:.4f}")
print(f"RECAST (full data): {sweep_nlls[-1]:.4f}")
crossover = [n for n, nll in zip(N_TRAIN_SIZES, sweep_nlls) if nll <= etas_test_nll]
if crossover:
    print(f"RECAST first beats ETAS at N_train ≥ {crossover[0]}")
else:
    print("RECAST does not yet beat ETAS with these training sizes / epoch budget.")
    print("Try increasing SWEEP_EPOCHS or N_CATALOGS in generate_etas_synthetic.py.")



#%%
# ─── Section 14: Conditional intensity figure (paper Fig. 2 equivalent) ───────
# Three-panel figure matching Dascher-Cousineau et al. (2023) Figure 2:
#
#   A (top-left):    Magnitude scatter plot; right axis shows N(t) (observed
#                    cumulative count) alongside the ETAS and RECAST compensators
#                    Λ(t) = ∫₀ᵗ λ(s) ds.  A good model has Λ(t) ≈ N(t).
#
#   B (bottom-left): ETAS and RECAST conditional intensity λ(t) on a log scale.
#                    Panels A and B share the time axis.
#
#   C (right):       Histogram of per-catalog NLL differences
#                    log L̃_RECAST − log L̃_ETAS for every train and test sequence.
#                    Values > 0 mean ETAS preferred; < 0 mean RECAST preferred.
#
# ETAS intensity / compensator use the temporal marginal of the spatio-temporal
# model.  Because ∫∫ g(x,y|parent) dx dy = 1, the spatial kernel drops out and
# the temporal intensity reduces to the standard Omori sum — consistent with
# what etas_baseline.nll_loss() uses for the compensator internally.
# RECAST uses model.evaluate_intensity() and model.evaluate_compensator().

import matplotlib.gridspec as gridspec


def etas_temporal_intensity(seq, m, t_grid):
    """Marginal temporal intensity: λ(t) = μ + Σ_{j<t} k·10^{α(m_j−Mc)}·(t−t_j+c)^{−p}"""
    times = seq.arrival_times.numpy()
    mags  = seq.mag.numpy()
    p, c  = m.p.item(), m.c.item()
    prod  = m.k.item() * 10 ** (m.alpha.item() * (mags - m.M_c.item()))
    dt     = t_grid[:, None] - times[None, :]       # (T, n)
    causal = dt > 0
    omori  = np.where(causal, (np.maximum(dt, 0) + c) ** (-p), 0.0)
    return m.mu.item() + (prod * omori * causal).sum(axis=1)


def etas_temporal_compensator(seq, m, t_grid):
    """Compensator: Λ(t) = μ·t + Σ_{j<t} k·10^{α(m_j−Mc)}·[(t−t_j+c)^{1−p}−c^{1−p}]/(1−p)"""
    times = seq.arrival_times.numpy()
    mags  = seq.mag.numpy()
    p, c  = m.p.item(), m.c.item()
    prod  = m.k.item() * 10 ** (m.alpha.item() * (mags - m.M_c.item()))
    dt      = t_grid[:, None] - times[None, :]      # (T, n)
    causal  = dt > 0
    omori_i = np.where(causal,
                       ((np.maximum(dt, 0) + c) ** (1 - p) - c ** (1 - p)) / (1 - p),
                       0.0)
    return m.mu.item() * t_grid + (prod * omori_i).sum(axis=1)


# ── Use the same reference sequence as Section 9 ─────────────────────────────
_seq  = seq_ref
_arr  = _seq.arrival_times.numpy()
_mags = _seq.mag.numpy()

# Dense time grid for ETAS (uniform); RECAST uses its own internal grid
_t_fine = np.linspace(float(_seq.t_start) + 1e-4, float(_seq.t_end) - 1e-4, 3000)

etas_int_vals  = etas_temporal_intensity(_seq, etas_baseline, _t_fine)
etas_comp_vals = etas_temporal_compensator(_seq, etas_baseline, _t_fine)

model.eval()
with torch.no_grad():
    _rt_int,  _ri_vals  = model.evaluate_intensity(_seq)
    _rt_comp, _rc_vals  = model.evaluate_compensator(_seq)

_rt_int   = _rt_int.numpy();   _ri_vals  = _ri_vals.numpy()
_rt_comp  = _rt_comp.numpy();  _rc_vals  = _rc_vals.numpy()

# N(t): step function starting at 0, incrementing at each arrival
_t_Nt = np.concatenate([[0.0], _arr])
_n_Nt = np.arange(len(_t_Nt))   # 0, 1, 2, …, n_events

# ── Per-sequence NLL for Panel C ─────────────────────────────────────────────
_train_batch_c = eq.data.Batch.from_list(train_seqs)
# test_batch is already in scope from Section 5

with torch.no_grad():
    _etas_nll_tr   = etas_baseline.nll_loss(_train_batch_c).numpy()
    _recast_nll_tr = model.nll_loss(_train_batch_c, window=WINDOW).numpy()
    _etas_nll_te   = etas_baseline.nll_loss(test_batch).numpy()
    _recast_nll_te = model.nll_loss(test_batch, window=WINDOW).numpy()

diff_train = _recast_nll_tr - _etas_nll_tr
diff_test  = _recast_nll_te - _etas_nll_te

# ── Figure ────────────────────────────────────────────────────────────────────
# ── Spatial forecasts for panels D / E ───────────────────────────────────────
# Both models are conditioned on the first `condition_days` of seq_ref and
# sampled N_SPATIAL times; the maps show mean events per cell per forecast.
# etas_2 uses the TRUE generative parameters.  (Evaluating the etas_2
# conditional intensity on a grid instead would only count first-generation
# triggering from the conditioning events, not cascades among forecast events,
# so it would not be comparable to RECAST's sampled maps.)
from matplotlib.colors import LogNorm

N_SPATIAL, KM_BIN_MAP = 50, 5.0
_cond_df = cond_seq_to_df(cond_seq)
_aux_end = T_REF + dt.timedelta(days=condition_days)
_sim_end = T_REF + dt.timedelta(days=float(seq_ref.t_end))

_rx, _ry = [], []
with torch.no_grad():
    _ens = model.sample(batch_size=N_SPATIAL, duration=forecast_days,
                        t_start=condition_days, past_seq=cond_seq, mag_completeness=MC)
for i in range(_ens.batch_size):
    keep = ~_ens.mask[i].bool()
    _rx.append(_ens.x_loc[i][keep].numpy())
    _ry.append(_ens.y_loc[i][keep].numpy())
_rx, _ry = np.concatenate(_rx), np.concatenate(_ry)

_ex, _ey = [], []
print(f"Simulating {N_SPATIAL} etas_2 continuations …")
for _ in range(N_SPATIAL):
    sim = simulate_catalog_continuation(
        auxiliary_catalog=_cond_df, auxiliary_start=T_REF, auxiliary_end=_aux_end,
        polygon=polygon, simulation_end=_sim_end, parameters=TRUE_PARAMS,
        mc=MC, beta_main=beta_main, m_max=MAG_MAX,
        filter_polygon=False, approx_times=True,
    )
    sim = sim[sim['time'] > _aux_end]
    _ex.append((sim['longitude'].values - LON_CTR) * KM_PER_LON)
    _ey.append((sim['latitude'].values - LAT_CTR) * KM_PER_LAT)
_ex, _ey = np.concatenate(_ex), np.concatenate(_ey)

_xe = np.arange(-HALF_KM_LON, HALF_KM_LON + KM_BIN_MAP, KM_BIN_MAP)
_ye = np.arange(-HALF_KM_LAT, HALF_KM_LAT + KM_BIN_MAP, KM_BIN_MAP)
_H_recast = np.histogram2d(_rx, _ry, bins=[_xe, _ye])[0] / N_SPATIAL
_H_etas   = np.histogram2d(_ex, _ey, bins=[_xe, _ye])[0] / N_SPATIAL
_norm = LogNorm(vmin=1 / N_SPATIAL, vmax=max(_H_recast.max(), _H_etas.max(), 1))

_fore = _arr > condition_days
_ox, _oy = _seq.x_loc.numpy()[_fore], _seq.y_loc.numpy()[_fore]
_om = _mags[_fore]

#%%
fig = plt.figure(figsize=(12, 10))

# ── Manual axes placement: [left, bottom, width, height] in figure fractions ──
# Edit these numbers to move / resize any panel.
POS_A  = [0.07, 0.72, 0.52, 0.19]
POS_B  = [0.07, 0.53, 0.52, 0.19]
POS_C  = [0.70, 0.53, 0.26, 0.38]
POS_D  = [0.07, 0.06, 0.45, 0.38]
POS_E  = [0.40, 0.06, 0.45, 0.38]
POS_CB = [0.8, 0.07, 0.015, 0.36]

ax_A  = fig.add_axes(POS_A)
ax_B  = fig.add_axes(POS_B, sharex=ax_A)
ax_C  = fig.add_axes(POS_C)
ax_D  = fig.add_axes(POS_D)
ax_E  = fig.add_axes(POS_E, sharex=ax_D, sharey=ax_D)
ax_cb = fig.add_axes(POS_CB)

# ── A: magnitude scatter (left axis) + N(t) / Λ(t) (right axis) ──────────────
ax_A.scatter(_arr, _mags, s=(_mags - MC + 0.5) ** 2 * 12,
             c='gray', alpha=0.55, zorder=2)
ax_A.set_ylabel("Magnitude")
ax_A.set_ylim(MC - 0.3, _mags.max() + 0.7)
plt.setp(ax_A.get_xticklabels(), visible=False)
ax_A.text(0.01, 1.10, 'A', transform=ax_A.transAxes,
          fontsize=12, fontweight='bold', va='top')

ax_A2 = ax_A.twinx()
ax_A2.step(_t_Nt, _n_Nt, where='post', color='gray',  lw=1.4, label='N(t)',   zorder=3)
ax_A2.plot(_t_fine,  etas_comp_vals, color='red',   lw=1.2, label='ETAS',   zorder=4)
ax_A2.plot(_rt_comp, _rc_vals,       color='black', lw=1.2, label='RECAST', zorder=4)
ax_A2.set_ylabel("Cumulative count / Λ(t)")
ax_A2.legend(fontsize=8, loc='upper left')

# ── B: conditional intensity λ(t) ─────────────────────────────────────────────

ax_B.plot(_t_fine, etas_int_vals, color='red',   lw=0.9, label='ETAS')
ax_B.plot(_rt_int, _ri_vals,      color='black', lw=0.9, label='RECAST')
ax_B.set_yscale('log')
ax_B.set_xlabel("Time (days)")
ax_B.set_ylabel("Intensity (events/day)")
ax_B.set_xlim(float(_seq.t_start), float(_seq.t_end))
ax_B.legend(fontsize=8)
ax_B.text(0.01, 0.97, 'B', transform=ax_B.transAxes,
          fontsize=12, fontweight='bold', va='top')

# ── C: per-catalog NLL difference histogram ────────────────────────────────────
_all_diffs = np.concatenate([diff_train, diff_test])
bins = np.linspace(_all_diffs.min(), _all_diffs.max(), 35)
ax_C.hist(diff_train, bins=bins, color='lightcoral', alpha=0.75, label=f'Train (n={len(diff_train)})')
ax_C.hist(diff_test,  bins=bins, color='gray',       alpha=0.75, label=f'Test  (n={len(diff_test)})')
ax_C.axvline(0, color='crimson', ls='--', lw=1.5)
ax_C.set_xlabel(
    r'$\log\tilde{\mathcal{L}}_\mathrm{RECAST} - \log\tilde{\mathcal{L}}_\mathrm{ETAS}$'
)
ax_C.set_ylabel("Number of sequences")
ax_C.legend(fontsize=8)
# Annotation matching the paper's "Preferred model" label
_xlim = ax_C.get_xlim()
_ymid = ax_C.get_ylim()[1] * 0.92
ax_C.annotate('', xy=(_xlim[0] + 0.02 * (_xlim[1]-_xlim[0]), _ymid),
              xytext=(0, _ymid),
              arrowprops=dict(arrowstyle='->', color='gray', lw=1.2))
ax_C.annotate('', xy=(_xlim[1] - 0.02 * (_xlim[1]-_xlim[0]), _ymid),
              xytext=(0, _ymid),
              arrowprops=dict(arrowstyle='->', color='gray', lw=1.2))
ax_C.text(0, _ymid, ' ETAS : RECAST ', ha='center', va='center',
          fontsize=7.5, color='gray',
          bbox=dict(fc='white', ec='none', pad=1))
ax_C.text(0.01, 0.97, 'C', transform=ax_C.transAxes,
          fontsize=12, fontweight='bold', va='top')

# ── D / E: spatial forecast maps ─────────────────────────────────────────────
for ax, H, name, letter in [(ax_D, _H_recast, 'RECAST', 'D'),
                            (ax_E, _H_etas, 'ETAS', 'E')]:
    pm = ax.pcolormesh(_xe, _ye, np.ma.masked_equal(H, 0).T, cmap='Blues', norm=_norm)
    ax.scatter(_ox, _oy, s=(_om - MC + 1) ** 2 * 12, facecolor='none',
               edgecolor='red', lw=0.8, label='Observed (forecast period)')
    ax.set_xlim(-HALF_KM_LON, HALF_KM_LON)
    ax.set_ylim(-HALF_KM_LAT, HALF_KM_LAT)
    ax.set_aspect('equal')
    ax.set_xlabel("East of box center (km)")
    ax.set_title(f"{name}\n{N_SPATIAL} forecasts, {KM_BIN_MAP:g} km cells", fontsize=9)
    ax.text(0.01, 0.97, letter, transform=ax.transAxes,
            fontsize=12, fontweight='bold', va='top')
ax_D.set_ylabel("North of box center (km)")
plt.setp(ax_E.get_yticklabels(), visible=False)
ax_D.legend(fontsize=8, loc='lower right')
fig.colorbar(pm, cax=ax_cb, label='Mean events per cell per forecast')

fig.suptitle(
    "RECAST performance on synthetic ETAS catalogs\n",
    #"(both NLLs: spatio-temporal likelihood of events in the box, per day and per km²)",
    fontsize=10, y=0.94,
)
plt.savefig(f"{FIGS_DIR}/conditional_intensity.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"\nPanel C summary:")
print(f"  Train: mean diff = {diff_train.mean():.4f}  "
      f"(+ve = ETAS preferred, −ve = RECAST preferred)")
print(f"  Test:  mean diff = {diff_test.mean():.4f}")

#%%
# ─── Section 15: ETAS parameter recovery from RECAST-generated catalogs ────────
# Test: if RECAST has learned the ETAS distribution, does inverting ETAS on
# RECAST-generated sequences recover the true parameters?
#
# Approach:
#   1. For N_SYN held-out test sequences, give RECAST the first _COND_DAYS days of
#      the REAL sequence (the seeded mainshock + early aftershocks) and let it
#      sample the remaining days.  Sampling unconditionally is not a fair test:
#      the etas_2 catalogs all start with a seeded M>=5.5 mainshock, which
#      RECAST's magnitude decoder (a context-dependent Gutenberg-Richter law)
#      cannot generate from scratch, and unconditional samples also lack the
#      mainshock-driven early rate.
#   2. Concatenate real-conditioning + sampled events into one catalog with
#      1-day buffers between sequences (so etas_2 sees a single time-series).
#      Caveat: events at the start of sequence i+1 appear to the inversion as
#      potential aftershocks of sequence i.  For typical M~3 events, Omori at
#      dt=1 day is (1+c)^{-p} * k0 ≈ 1.0 * 0.003 ≈ 0.003 — negligible vs the
#      background rate of ~0.5 events/day.  Larger events near sequence
#      boundaries produce more contamination but are rare.  mu is underestimated
#      by the gap fraction: true_mu = recovered_mu * (T_DAYS + 1) / T_DAYS.
#   3. Run ETASParameterCalculation on the concatenated catalog.
#   4. Cache to JSON; skip inversion on subsequent runs.
#   5. Print recovery table comparing true vs recovered parameters.
#
# Reading the table: etas_2's k0, a, d, rho are strongly degenerate (the
# offspring rate depends on k0·(π/ρ)·d^(−ρ) and a − ρ·γ), so individual values can
# wander to the optimizer's bounds while the physical combinations stay correct.
# The table therefore also reports the identifiable derived quantities
#     alpha = (a − ρ·γ) / ln 10      (RECAST ETAS productivity exponent)
#     k     = k0 · (π/ρ) · d^(−ρ)    (RECAST ETAS productivity)
# and flags any raw parameter sitting at an inversion bound (not a real estimate).
# Control (real etas_2 catalogs through this same pipeline) recovers all raw
# parameters except log10_tau, which is poorly identified from 30-day windows.

from etas.inversion import (
    ETASParameterCalculation,
    LOG10_MU_RANGE, LOG10_K0_RANGE, A_RANGE, LOG10_C_RANGE, OMEGA_RANGE,
    LOG10_TAU_RANGE, LOG10_D_RANGE, GAMMA_RANGE, RHO_RANGE,
)

_RECOVERY_JSON = f"{SAVE_DIR}/recast_etas_recovery_conditioned.json"
_N_SYN         = min(100, len(test_seqs))
_COND_DAYS     = 1.0    # days of the real sequence given to RECAST as history
_SEQ_GAP_DAYS  = 1.0    # buffer between concatenated sequences (days)

if not os.path.exists(_RECOVERY_JSON):
    # ── 1. Sample from RECAST, conditioned on the real early events ───────────
    print(f"Sampling {_N_SYN} RECAST continuations, each conditioned on the first "
          f"{_COND_DAYS:g} day(s) of a held-out real sequence …")
    model.eval()
    rows, _n_outside, _n_sim, _n_cond = [], 0, 0, 0
    for i, ref in enumerate(test_seqs[:_N_SYN]):
        cond = ref.get_subsequence(ref.t_start, _COND_DAYS)
        with torch.no_grad():
            out = model.sample(
                batch_size       = 1,
                duration         = float(ref.t_end) - _COND_DAYS,
                t_start          = _COND_DAYS,
                past_seq         = cond,
                mag_completeness = MC,
            ).to_list()[0]
        new = out.arrival_times.numpy() > _COND_DAYS      # drop any echoed history
        arr  = np.concatenate([cond.arrival_times.numpy(), out.arrival_times.numpy()[new]])
        mags = np.concatenate([cond.mag.numpy(),           out.mag.numpy()[new]])
        x_km = np.concatenate([cond.x_loc.numpy(),         out.x_loc.numpy()[new]])
        y_km = np.concatenate([cond.y_loc.numpy(),         out.y_loc.numpy()[new]])
        _n_cond += cond.num_events
        _n_sim  += int(new.sum())
        sim_x, sim_y = out.x_loc.numpy()[new], out.y_loc.numpy()[new]
        _n_outside += int(((np.abs(sim_x) > HALF_KM_LON) | (np.abs(sim_y) > HALF_KM_LAT)).sum())

        t_offset = i * (float(T_DAYS) + _SEQ_GAP_DAYS)    # absolute day offset
        lats = y_km / KM_PER_LAT + LAT_CTR
        lons = x_km / KM_PER_LON + LON_CTR
        for j in range(len(arr)):
            rows.append({
                'id':        f's{i}_e{j}',
                'latitude':  float(lats[j]),
                'longitude': float(lons[j]),
                'time':      T_REF + dt.timedelta(days=float(t_offset + arr[j])),
                'magnitude': float(mags[j]),
            })
    print(f"  {_n_cond} real conditioning events + {_n_sim} sampled events "
          f"({_n_sim / _N_SYN:.1f} sampled/seq); "
          f"{_n_outside} sampled events outside the box ({_n_outside / max(_n_sim, 1):.1%}, "
          "dropped by etas_2)")

    _cat_df = pd.DataFrame(rows).sort_values('time').reset_index(drop=True)
    total_cat_days = _N_SYN * (float(T_DAYS) + _SEQ_GAP_DAYS)
    t_inv_start = T_REF
    t_inv_end   = T_REF + dt.timedelta(days=total_cat_days)
    print(f"  Catalog: {len(_cat_df)} events over {total_cat_days:.0f} days")

    # ── 3. Run etas_2 inversion ───────────────────────────────────────────────
    _shape_coords = [
        [LAT_MIN, LON_MIN], [LAT_MAX, LON_MIN],
        [LAT_MAX, LON_MAX], [LAT_MIN, LON_MAX],
    ]
    _inv_meta = {
        'catalog':               _cat_df,
        'auxiliary_start':       t_inv_start,   # no auxiliary events
        'timewindow_start':      t_inv_start,
        'timewindow_end':        t_inv_end,
        'mc':                    MC,
        'delta_m':               0.1,
        'coppersmith_multiplier': 100,
        'shape_coords':          _shape_coords,
        'theta_0':               TRUE_PARAMS,   # warm start: converges faster
    }
    print("Running etas_2 inversion (may take a few minutes) …")
    _calc = ETASParameterCalculation(_inv_meta)
    _calc.prepare()
    _recovered = _calc.invert()

    with open(_RECOVERY_JSON, 'w') as _f:
        import json as _json
        # Convert numpy scalars to Python floats for JSON serialisation
        _json.dump({'recovered': {k: (float(v) if v is not None else None)
                                  for k, v in _recovered.items()},
                    'n_events': len(_cat_df),
                    'n_sequences': _N_SYN, 'total_days': total_cat_days,
                    'cond_days': _COND_DAYS}, _f, indent=2)
    print(f"  Saved to {_RECOVERY_JSON}")
else:
    import json as _json
    with open(_RECOVERY_JSON) as _f:
        _cache = _json.load(_f)
    _recovered = _cache['recovered']
    print(f"Loaded cached inversion from {_RECOVERY_JSON}")

# ── 4. Recovery table ─────────────────────────────────────────────────────────
# mu requires a gap correction: the inversion spreads mu over the full time
# window including inter-sequence buffers, but events only occur in active
# windows of length T_DAYS per sequence.
_gap_correction   = (float(T_DAYS) + _SEQ_GAP_DAYS) / float(T_DAYS)
_mu_correction_db = math.log10(_gap_correction)  # add to recovered log10_mu


def _with_derived(par):
    """Add the identifiable productivity combinations to an etas_2 parameter dict."""
    out = dict(par)
    out['alpha'] = (par['a'] - par['rho'] * par['gamma']) / math.log(10)
    out['k_rec'] = (10 ** par['log10_k0'] * math.pi / par['rho']
                    * (10 ** par['log10_d']) ** (-par['rho']))
    return out


_true_all = _with_derived(TRUE_PARAMS)
_rec_all  = _with_derived(_recovered)

_bounds = {
    'log10_mu': LOG10_MU_RANGE, 'log10_k0': LOG10_K0_RANGE, 'a': A_RANGE,
    'log10_c': LOG10_C_RANGE, 'omega': OMEGA_RANGE, 'log10_tau': LOG10_TAU_RANGE,
    'log10_d': LOG10_D_RANGE, 'gamma': GAMMA_RANGE, 'rho': RHO_RANGE,
}


def _at_bound(key, val, tol=0.02):
    """True if val lies within tol·(range width) of either etas_2 inversion bound."""
    if key not in _bounds or val is None:
        return False
    lo, hi = _bounds[key]
    return val <= lo + tol * (hi - lo) or val >= hi - tol * (hi - lo)


_param_meta = [
    # (display label, key in _true_all, key in _rec_all, additive correction, note)
    ('log10_μ',   'log10_mu',  'log10_mu',   _mu_correction_db, '(+gap corr)'),
    ('log10_ι',   None,        'log10_iota', 0.0,               '(no true val)'),
    ('log10_k0',  'log10_k0',  'log10_k0',   0.0,               ''),
    ('a',         'a',         'a',           0.0,               ''),
    ('log10_c',   'log10_c',  'log10_c',     0.0,               ''),
    ('ω (p−1)',   'omega',     'omega',       0.0,               ''),
    ('log10_τ',   'log10_tau', 'log10_tau',   0.0,               ''),
    ('log10_d',   'log10_d',  'log10_d',     0.0,               ''),
    ('γ',         'gamma',     'gamma',       0.0,               ''),
    ('ρ',         'rho',       'rho',         0.0,               ''),
    # Identifiable combinations (RECAST-ETAS convention); not degenerate like k0/a/d/ρ
    ('α (derived)', 'alpha',   'alpha',       0.0,               '(a−ργ)/ln10'),
    ('k (derived)', 'k_rec',   'k_rec',       0.0,               'k0·π/ρ·d^−ρ'),
]

_hr = "─" * 78
print(f"\n{_hr}")
print(f"  {'Parameter':<12}  {'True':>10}  {'Recovered':>10}  {'Corrected':>10}  {'Δ':>8}")
print("  " + "─"*12 + "  " + "─"*10 + "  " + "─"*10 + "  " + "─"*10 + "  " + "─"*8)
for label, true_key, rec_key, corr, note in _param_meta:
    t_val = _true_all[true_key] if true_key is not None else None
    r_val = _rec_all[rec_key]
    t_str = f"{t_val:>10.4f}" if t_val is not None else f"{'—':>10}"
    if r_val is None:
        r_str = f"{'—':>10}";  c_str = f"{'—':>10}";  d_str = f"{'—':>8}"
    else:
        r_corr = r_val + corr
        r_str  = f"{r_val:>10.4f}"
        c_str  = f"{r_corr:>10.4f}"
        d_str  = f"{r_corr - t_val:>+8.4f}" if t_val is not None else f"{'—':>8}"
    if _at_bound(rec_key, r_val):
        note = (note + " ⚠ AT BOUND").strip()
    print(f"  {label:<12}  {t_str}  {r_str}  {c_str}  {d_str}  {note}")
print(f"  {_hr}")
print("  ⚠ AT BOUND: optimizer hit an etas_2 limit — not an estimate. k0, a, d, ρ trade off;")
print("    judge productivity by the derived α and k rows, not the raw values.")

# ── 5. Recovery bar chart ─────────────────────────────────────────────────────
# Exclude params with no true value from the comparison bar chart
_chart_rows = [(l, tk, rk, c) for l, tk, rk, c, _ in _param_meta if tk is not None]
_labels  = [r[0] + ("*" if _at_bound(r[2], _rec_all[r[2]]) else "") for r in _chart_rows]
_true_v  = [_true_all[r[1]] for r in _chart_rows]
_rec_v   = [_rec_all[r[2]] + r[3] for r in _chart_rows]

x = np.arange(len(_labels))
w = 0.35
fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(x - w/2, _true_v, w, label='True (generating)',  color='steelblue', alpha=0.85)
ax.bar(x + w/2, _rec_v,  w, label='Recovered (RECAST→etas_2)', color='tomato',    alpha=0.85)
ax.set_xticks(x)
ax.set_xticklabels(_labels, fontsize=9)
ax.set_ylabel("Parameter value")
ax.set_title(
    f"ETAS parameter recovery from {_N_SYN} RECAST continuations "
    f"(conditioned on first {_COND_DAYS:g} d of real sequences)\n"
    f"(μ corrected for {_SEQ_GAP_DAYS:.0f}-day buffer; * = at inversion bound; "
    "α, k derived)"
)
ax.legend(fontsize=9)
ax.axhline(0, color='gray', lw=0.7, ls='--')
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/etas_recovery_recast.png", dpi=150, bbox_inches='tight')
plt.show()

# %%
